package humanize

// synPackMo is the Moldovan/Romanian synonym dictionary.
// Comprehensive coverage: verbs (all forms), articulated/indefinite nouns,
// adjectives, months, days, seasons, family, health, technology, money.
var synPackMo = dictPack{
	AICliches: map[string]string{
		"a accepta": "a admite",
		"a aduce": "a transporta",
		"a ajuta": "a sprijini",
		"a alerga": "a goni",
		"a aminti": "a evoca",
		"a aprinde": "a incendia",
		"a arăta": "a demonstra",
		"a asculta": "a auzi atent",
		"a ascunde": "a tăinui",
		"a auzi": "a percepe",
		"a avea": "a deține",
		"a aștepta": "a anticipa",
		"a bea": "a savura",
		"a cere": "a solicita",
		"a cincea": "în poziția cinci",
		"a citi": "a parcurge",
		"a coborî": "a descinde",
		"a construi": "a edifica",
		"a continua": "a persevera",
		"a crede": "a considera",
		"a cumpăra": "a procura",
		"a cânta": "a interpreta",
		"a câștiga": "a obține",
		"a cădea": "a se prăbuşi",
		"a căsători": "a uni în matrimoniu",
		"a căuta": "a investiga",
		"a da": "a oferi",
		"a dansa": "a se mișca ritmic",
		"a deschide": "a descoperi",
		"a descălța": "a decalița",
		"a desface": "a desfășura",
		"a deveni": "a se transforma",
		"a dezbrăca": "a denuda",
		"a divorța": "a se separa",
		"a dori": "a tânji",
		"a dormi": "a se odihni",
		"a doua": "următoarea",
		"a duce": "a transporta",
		"a expira": "a exhala",
		"a face": "a efectua",
		"a felicita": "a complimenta",
		"a fi": "a exista",
		"a folosi": "a utiliza",
		"a gândi": "a chibzui",
		"a găsi": "a descoperi",
		"a inhala": "a inspira aer",
		"a invita": "a chema",
		"a iubi": "a adora",
		"a juca": "a se distra",
		"a lua": "a prelua",
		"a lucra": "a presta",
		"a merge": "a se deplasa",
		"a mulțumi": "a manifesta recunoștință",
		"a munci": "a depune efort",
		"a muri": "a deceda",
		"a mânca": "a consuma",
		"a oferi": "a furniza",
		"a opri": "a stopa",
		"a patra": "în poziția patru",
		"a periclita": "a primejdui",
		"a pierde": "a rătăci",
		"a pleca": "a se îndepărta",
		"a plăti": "a remunera",
		"a porni": "a iniția",
		"a precede": "a anteceda",
		"a primi": "a obține",
		"a privi": "a contempla",
		"a promite": "a făgădui",
		"a refuza": "a respinge",
		"a repara": "a restaura",
		"a respira": "a inhala",
		"a răspunde": "a replica",
		"a saluta": "a face reverență",
		"a salva": "a izbăvi",
		"a schimba": "a modifica",
		"a scrie": "a redacta",
		"a se aseza": "a se instala",
		"a se așeza": "a se aşeza pe loc",
		"a se culca": "a se aşeza orizontal",
		"a se naște": "a veni pe lume",
		"a se opri": "a face pauză",
		"a se ridica": "a se înălța",
		"a se trezi": "a se deştepta",
		"a se vindeca": "a se restabili",
		"a se îmbolnăvi": "a se infirma",
		"a se îndrăgosti": "a iubi pasionat",
		"a sosi": "a ajunge",
		"a spune": "a comunica",
		"a sta": "a se afla",
		"a stinge": "a extingere",
		"a strica": "a distruge",
		"a striga": "a vocifera",
		"a strânge": "a aduna",
		"a strănuta": "a expectora cu zgomot",
		"a sufla": "a sufla aer",
		"a sări": "a salta",
		"a termina": "a finaliza",
		"a tinereți": "a întineri",
		"a treia": "în poziția trei",
		"a trăi": "a viețui",
		"a tuși": "a expectora",
		"a tăcea": "a păstra tăcerea",
		"a uita": "a omite",
		"a uni": "a amalgama",
		"a urca": "a ascende",
		"a uri": "a detesta",
		"a urma": "a succeda",
		"a urî": "a detesta",
		"a vedea": "a observa",
		"a veni": "a sosi",
		"a vinde": "a tranzacționa",
		"a vorbi": "a comunica",
		"a vrea": "a aspira",
		"a zbura": "a plana",
		"a zice": "a declara",
		"a îmbrăca": "a vestmânta",
		"a îmbătrâni": "a se senesce",
		"a împărți": "a divide",
		"a începe": "a iniția",
		"a încerca": "a se strădui",
		"a închide": "a sigila",
		"a încălța": "a calița",
		"a îndoi": "a flexa",
		"a îndrepta": "a rectifica",
		"a înota": "a se mişca în apă",
		"a întreba": "a interoga",
		"a întâmpina": "a saluta",
		"a învăța": "a studia",
		"a înțelege": "a sesiza",
		"a șopti": "a murmura",
		"a ști": "a cunoaște",
		"absolut": "categoric",
		"acea": "acea anume",
		"aceasta": "această anume",
		"această": "această anume",
		"acei": "acei anume",
		"acel": "acel anume",
		"acele": "acele anume",
		"acelea": "acele anumea",
		"acest": "acest anume",
		"aceste": "aceste anume",
		"acestea": "aceste anumea",
		"acești": "acești anume",
		"acolo": "în acel loc",
		"acoperiș": "învelitoare",
		"acoperișuri": "învelitori",
		"acru": "lemonic",
		"actor": "artist scenic",
		"actori": "artiști scenici",
		"acum": "în prezent",
		"acțiune": "demers",
		"acțiunea": "demersa",
		"acțiuni": "demersuri",
		"adesea": "frecvent",
		"adevăr": "veridicitate",
		"adevărat": "veridic",
		"adevărata": "veridica",
		"adevărate": "veridice",
		"adevăratea": "veridicea",
		"adevărată": "veridică",
		"adevărați": "veridici",
		"adevăruri": "veridicități",
		"admir": "stimez",
		"admirat": "stimat",
		"admiri": "stimezi",
		"admiră": "stimează",
		"admirăm": "stimăm",
		"adormit": "în somn",
		"adormită": "în somn",
		"aer": "atmosferă",
		"aere": "atmosfere",
		"aerea": "atmosferea",
		"aeroport": "port aerian",
		"afara": "exterior",
		"afară": "în exterior",
		"agitat": "neliniștit",
		"agitate": "neliniștite",
		"agitată": "neliniștită",
		"agitați": "neliniștiți",
		"aici": "în acest loc",
		"ajut": "sprijin",
		"ajuta": "sprijinea",
		"ajutat": "sprijinit",
		"ajută": "sprijini",
		"al cincilea": "în poziția cinci",
		"al doilea": "următorul",
		"al patrulea": "în poziția patru",
		"al treilea": "în poziția trei",
		"alb": "imaculat",
		"alba": "imaculata",
		"albastra": "azura",
		"albastre": "azure",
		"albastrea": "azurea",
		"albastru": "azur",
		"albastră": "azură",
		"albaștri": "azuri",
		"albe": "imaculate",
		"albea": "imaculatea",
		"albi": "imaculați",
		"albă": "imaculată",
		"alearga": "goni",
		"aleargă": "goni",
		"alerga": "gonea",
		"alergat": "gonit",
		"alergia": "hipersensibilitatea",
		"alergie": "hipersensibilitate",
		"alergii": "hipersensibilități",
		"alergiile": "hipersensibilitățile",
		"amabil": "drăguț",
		"amabila": "drăguța",
		"amabile": "drăguțe",
		"amabilea": "drăguțea",
		"amabili": "drăguți",
		"amabilă": "drăguță",
		"amar": "amărui",
		"amenințare": "intimidare",
		"amenințarea": "intimidarea",
		"an": "perioadă anuală",
		"angajat": "salariat",
		"angajator": "patron",
		"ani": "annumuri",
		"animal": "creatură",
		"animale": "creaturi",
		"animalea": "creaturia",
		"antic": "primordial",
		"antrenor": "instructor",
		"anul": "perioada anuală",
		"apa": "lichid",
		"ape": "lichide",
		"apea": "lichidea",
		"apreciat": "evaluat pozitiv",
		"apreciază": "evaluează pozitiv",
		"apreciez": "evaluez pozitiv",
		"aprilie": "a patra lună a anului",
		"aproape": "în proximitate",
		"aproapea": "în proximitatea",
		"apă": "lichid",
		"apăr": "protejez",
		"apărare": "protecție",
		"apărarea": "protecțiea",
		"apărat": "protejat",
		"apără": "protejază",
		"aragaz": "cuptor cu gaz",
		"aragazul": "cuptorul cu gaz",
		"arata": "demonstra",
		"arată": "demonstra",
		"are": "deține",
		"area": "deținea",
		"arhitect": "proiectant",
		"arta": "expresie creativa",
		"arte": "expresii creative",
		"artea": "expresii creativea",
		"articol": "scriere",
		"artist": "creator",
		"artiști": "creatori",
		"artă": "expresie creativă",
		"arăt": "demonstrez",
		"arăta": "demonstra",
		"arătat": "demonstrat",
		"ascult": "aud cu atenție",
		"asculta": "atent",
		"ascultat": "auzi atent",
		"ascultă": "atent",
		"ascultăm": "auzim cu atenție",
		"asculți": "auzi cu atenție",
		"ascuns": "tăinuit",
		"asistent": "auxiliar",
		"aspra": "severa",
		"aspre": "severe",
		"asprea": "severea",
		"aspri": "severi",
		"aspru": "sever",
		"aspră": "severă",
		"astăzi": "în ziua curentă",
		"atac": "asaltez",
		"atacat": "asaltat",
		"atacă": "asaltază",
		"atent": "scrupulos",
		"atunci": "în acel moment",
		"au": "dețin",
		"aud": "percep",
		"aude": "percepe",
		"audea": "percepea",
		"audibil": "discernibil",
		"august": "a opta lună a anului",
		"autobuz": "vehicul de transport public",
		"automobil": "vehicul",
		"auzea": "percepea",
		"auzit": "percepet",
		"avea": "deținea",
		"aveau": "dețineau",
		"avion": "aeronavă",
		"avut": "deținet",
		"așa este": "este corect",
		"baie": "spațiu sanitar",
		"baiea": "spațiu sanitara",
		"ban": "monedă mică",
		"banana": "fruct tropical",
		"banană": "fruct tropical",
		"banca": "instituție financiara",
		"bancnota": "hârtia monetară",
		"bancnotă": "hârtie monetară",
		"bancă": "instituție financiară",
		"bani": "mijloace de plată",
		"banul": "moneda mică",
		"bar": "local de băuturi",
		"barca": "ambarcațiune",
		"barcă": "ambarcațiune",
		"bea": "savura",
		"beau": "savurez",
		"bei": "savurezi",
		"bem": "savurăm",
		"benefic": "salutar",
		"bicicleta": "vehicul cu două roți",
		"bicicletă": "vehicul cu două roți",
		"bine": "virtute",
		"binea": "virtutea",
		"binevenit": "salutat",
		"binevoitoare": "amabile",
		"binevoitoarea": "amabilea",
		"binevoitor": "amabil",
		"binevoitori": "amabili",
		"blestem": "îmi exprim ura",
		"blestemă": "își exprimă ura",
		"blând": "tandru",
		"blânda": "tandra",
		"blânde": "tandre",
		"blândea": "tandrea",
		"blândă": "tandră",
		"blânzi": "tandri",
		"boala": "afecțiunea medicală",
		"boală": "afecțiune medicală",
		"bogat": "opulent",
		"bogata": "opulenta",
		"bogate": "opulente",
		"bogatea": "opulentea",
		"bogată": "opulentă",
		"bogați": "opulenți",
		"bogăția": "opulența",
		"bogăție": "opulență",
		"boli": "afecțiuni medicale",
		"bolile": "afecțiunile medicale",
		"bolnav": "suferind",
		"bolnava": "suferinda",
		"bolnave": "suferinde",
		"bolnavea": "suferindea",
		"bolnavi": "suferinzi",
		"bolnavă": "suferindă",
		"borcan": "recipient de conservare",
		"borcanul": "recipientul de conservare",
		"braț": "membru superior",
		"brațe": "membre superioare",
		"brațul": "membrul superior",
		"broasca": "amfibianul",
		"broască": "amfibian",
		"brusc": "neașteptat",
		"brânza": "produs lactat",
		"brânză": "produs lactat",
		"bucurie": "jubilație",
		"bucuriea": "jubilațiea",
		"bucurii": "jubilații",
		"bucătar": "culinar",
		"bucătărie": "spațiu culinar",
		"bucătăriea": "spațiu culinara",
		"bucătării": "spații culinare",
		"bumbac": "fibră vegetală",
		"bumbacul": "fibra vegetală",
		"bun": "excelent",
		"buna": "excelenta",
		"bune": "excelente",
		"bunea": "excelentea",
		"buni": "excelenți",
		"bunic": "ascendent matur",
		"bunica": "ascendenta matură",
		"bunicul": "ascendentul matur",
		"bunică": "ascendentă matură",
		"bună": "excelentă",
		"bună dimineața": "salutări matinale",
		"bună seara": "salutări vesperale",
		"bună ziua": "salutări diurne",
		"bunătate": "benevolență",
		"bunătatea": "benevolențăa",
		"bunătăți": "benevolențe",
		"burta": "abdomenul",
		"burtă": "abdomen",
		"băi": "spații sanitare",
		"băiat": "tânăr",
		"băiatul": "tânărul",
		"băieți": "tineri",
		"băieții": "tinerii",
		"bărbat": "domn",
		"bărbatul": "domnul",
		"bărbați": "domni",
		"bărbații": "domnii",
		"bătrân": "vârstnic",
		"bătrâna": "vârstnica",
		"bătrâne": "vârstnice",
		"bătrânea": "vârstnicea",
		"bătrâni": "vârstnici",
		"bătrână": "vârstnică",
		"băut": "savurat",
		"băutura": "lichid",
		"băuturi": "lichide",
		"băutură": "lichid",
		"cafea": "băutură caldă tonică",
		"cafenea": "local de cafea",
		"cai": "armăsari",
		"caiet": "registru școlar",
		"caii": "armăsarii",
		"cal": "armăsar",
		"calculator": "dispozitiv electronic",
		"calculatorul": "dispozitivul electronic",
		"cald": "tepid",
		"calda": "tepida",
		"calde": "tepide",
		"caldea": "tepidea",
		"caldă": "tepidă",
		"calm": "imperturbabil",
		"calma": "imperturbabila",
		"calmat": "potolit",
		"calme": "imperturbabile",
		"calmea": "imperturbabilea",
		"calmează": "potolește",
		"calmez": "potolesc",
		"calmi": "imperturbabili",
		"calmă": "imperturbabilă",
		"calul": "armăsarul",
		"calzi": "tepizi",
		"camera": "încăpere",
		"camere": "încăperi",
		"camerea": "încăperia",
		"cameră": "încăpere",
		"cana": "recipientul pentru băut",
		"canapea": "sofa",
		"canapeaua": "sofa-ua",
		"canapele": "sofale",
		"cană": "recipient pentru băut",
		"cap": "craniu",
		"capete": "cranii",
		"capetea": "craniia",
		"capra": "caprina",
		"capre": "caprine",
		"capră": "caprină",
		"capul": "craniul",
		"caracter": "personalitate",
		"caractere": "personalități",
		"caracterea": "personalităția",
		"card bancar": "instrument de plată",
		"carne": "țesut muscular",
		"carnea": "țesut musculara",
		"carte": "tom literar",
		"cartea": "tom literara",
		"cartof": "tubercul",
		"casa": "locuința",
		"case": "locuințe",
		"casea": "locuințea",
		"casele": "locuințele",
		"caselea": "locuințelea",
		"castravete": "cucurbitacee",
		"castravetea": "cucurbitaceea",
		"casă": "locuință",
		"cauta": "investiga",
		"caută": "investiga",
		"cauza": "origine",
		"cauze": "origini",
		"cauzea": "originia",
		"cauză": "origine",
		"ce mai faci": "cum te simți",
		"cea mai bună": "optimală",
		"cea mai rea": "abismală",
		"ceai": "infuzie de plante",
		"ceainic": "vas pentru fierbere",
		"ceainicul": "vasul pentru fierbere",
		"ceapa": "bulboasa",
		"ceapă": "bulboasă",
		"ceas": "horometru",
		"ceasuri": "horometre",
		"ceața": "negura",
		"ceață": "negură",
		"cel mai bun": "optimal",
		"cel mai mare": "maximal",
		"cel mai mic": "minimal",
		"cel mai rău": "abismal",
		"celebru": "renumit",
		"cer": "firmament",
		"certificat": "atestat",
		"certificatul": "atestatul",
		"ceruri": "firmamente",
		"cheie": "instrument de deschidere",
		"cheiea": "instrument de deschiderea",
		"cinci": "cvintet",
		"cincisprezece": "15 unități",
		"cincizeci": "50 unități",
		"cinema": "loc de filme",
		"ciorapi": "îmbrăcăminte pentru picioare",
		"ciorapii": "îmbrăcămintea pentru picioare",
		"citea": "parcurgea",
		"citesc": "parcurg",
		"citește": "parcurge",
		"citeștea": "parcurgea",
		"citești": "parcurgi",
		"citim": "parcurgem",
		"citit": "parcurget",
		"ciudat": "bizar",
		"cizme": "încălțăminte înaltă",
		"cizmele": "încălțămintea înaltă",
		"clar": "limpede",
		"cocoș": "masculul găinii",
		"cocoșul": "masculul găinii",
		"colaborat": "cooperat",
		"colaborează": "cooperează",
		"colaborez": "cooperez",
		"complecși": "intricați",
		"complet": "integral",
		"complex": "intricat",
		"complexa": "intricata",
		"complexe": "intricate",
		"complexea": "intricatea",
		"complexă": "intricată",
		"comportament": "conduită",
		"comportamente": "conduite",
		"comportamentea": "conduitea",
		"compozitor": "creator muzical",
		"computer": "calculator electronic",
		"computere": "calculatoare electronice",
		"computerea": "calculatoare electronicea",
		"compătimesc": "simt empatie",
		"compătimește": "simte empatie",
		"compătimit": "simțit empatie",
		"comun": "ubicuu",
		"concert": "manifestare muzicală",
		"concurat": "rivalizat",
		"concurează": "rivalizează",
		"concurez": "rivalizez",
		"conducător": "lider",
		"conducători": "lideri",
		"constant": "consecvent",
		"construia": "edifica",
		"construiește": "edifica",
		"construieștea": "edifica",
		"construit": "edificat",
		"conștiința": "moralitate",
		"conștiință": "moralitate",
		"copac": "arbore",
		"copaci": "arbori",
		"copii": "tineri",
		"copiii": "tinerii",
		"copil": "tânăr",
		"copilul": "tânărul",
		"cot": "articulație humerală",
		"cotul": "articulația humerală",
		"covor": "așternut pe podea",
		"cred": "consider",
		"crede": "consideră",
		"credea": "considera",
		"credem": "considerăm",
		"credit": "împrumut",
		"credite": "împrumuturi",
		"creditele": "împrumuturile",
		"creditul": "împrumutul",
		"creier": "encefal",
		"creiere": "encefale",
		"creierea": "encefalea",
		"creierul": "encefalul",
		"creion": "stilou cu grafit",
		"crezi": "consideri",
		"crezut": "considerat",
		"critic": "cenzurez",
		"criticat": "cenzurat",
		"critică": "cenzurează",
		"cruzime": "barbarie",
		"cruzimea": "barbariea",
		"cruzimi": "barbarii",
		"cu grijă": "cu prudență",
		"culoare": "nuanță",
		"culoarea": "nuanța",
		"cultura": "civilizație",
		"cultural": "civilizat",
		"culturi": "civilizații",
		"cultură": "civilizație",
		"cum te simți": "care e starea ta",
		"cumpăra": "procura",
		"cumpărat": "procurat",
		"cumpără": "procura",
		"cumpărător": "client",
		"cunoaștere": "erudiție",
		"cunoașterea": "erudițiea",
		"curaj": "îndrăzneală",
		"curaje": "îndrăzneală",
		"curajea": "îndrăznealăa",
		"curajoase": "neînfricate",
		"curajoasă": "neînfricată",
		"curajos": "neînfricat",
		"curajoși": "neînfricați",
		"curat": "imaculat",
		"curata": "imaculata",
		"curate": "imaculate",
		"curatea": "imaculatea",
		"curată": "imaculată",
		"curați": "imaculați",
		"curioasă": "iscoditoare",
		"curios": "iscoditor",
		"curs": "ciclu de instruire",
		"cursul": "ciclul de instruire",
		"cursuri": "cicluri de instruire",
		"cursurile": "ciclurile de instruire",
		"curând": "în curând",
		"cuțit": "instrument tăios",
		"cuțite": "instrumente tăioase",
		"cuțitul": "instrumentul tăios",
		"câine": "canid",
		"câinea": "canida",
		"câini": "canide",
		"cânta": "interpreta",
		"cântat": "interpretat",
		"cântec": "compoziție",
		"cântece": "compoziții",
		"cântecea": "compozițiia",
		"cântă": "interpreta",
		"cântăreț": "vocalist",
		"căciula": "acoperământul de cap",
		"căciulă": "acoperământ de cap",
		"cămașa": "tunica",
		"cămașă": "tunică",
		"cămăși": "tunici",
		"căpitan": "comandant naval",
		"cărți": "tomuri literare",
		"căuta": "investiga",
		"căutat": "investigat",
		"dansat": "se mișca ritmic",
		"danseaza": "ritmic",
		"dansează": "ritmic",
		"dat": "oferit",
		"datoria": "obligația financiară",
		"datorie": "obligație financiară",
		"datorii": "obligații financiare",
		"datoriile": "obligațiile financiare",
		"dau": "oferă",
		"de obicei": "în mod obișnuit",
		"deasupra": "în partea superioară",
		"decembrie": "a douăsprezecea lună a anului",
		"decenii": "decade",
		"deceniu": "decadă",
		"dedesubt": "în partea inferioară",
		"deget": "falangă",
		"degete": "falange",
		"degetul": "falanga",
		"deja": "anterior",
		"delicios": "savuros",
		"departe": "la distanță mare",
		"departea": "la distanțăa",
		"deputat": "parlamentar",
		"deranjat": "perturbat",
		"deranjează": "perturbă",
		"deranjez": "perturb",
		"deschide": "descoperi",
		"deschidea": "descoperea",
		"deschis": "descoperit",
		"deseori": "cu frecvență mare",
		"desigur": "indubitabil",
		"devenea": "se transforma",
		"devenit": "se transforma",
		"devine": "transforma",
		"devinea": "transforma",
		"devreme": "prematur",
		"devremea": "prematura",
		"deșteapta": "inteligenta",
		"deșteaptă": "perspicace",
		"deștept": "perspicace",
		"deștepte": "perspicace",
		"deșteptea": "inteligentea",
		"deștepți": "perspicace",
		"dicționar": "lexicon",
		"dicționarul": "lexiconul",
		"diferit": "disparat",
		"dificil": "anevoios",
		"dimineața": "amurg matinal",
		"dimineață": "amurg matinal",
		"dimineți": "amurguri matinale",
		"din nou": "din nou",
		"dinte": "molar",
		"dintea": "molara",
		"dintele": "organul dentar",
		"dinți": "organe dentare",
		"diploma": "actul de absolvire",
		"diplomă": "act de absolvire",
		"director": "administrator",
		"disprețuiesc": "desconsider",
		"disprețuiește": "desconsideră",
		"disprețuiești": "desconsideri",
		"disprețuit": "desconsiderat",
		"distrat": "amuzat",
		"distrează": "amuzează",
		"distrez": "amuz",
		"doarme": "odihni",
		"doarmea": "odihnia",
		"doi": "pereche",
		"doisprezece": "duzină",
		"dorea": "tânjea",
		"doresc": "tânjesc",
		"dorește": "tânji",
		"doreștea": "tânjia",
		"dorești": "tânjești",
		"dorim": "tânjim",
		"dorința": "năzuința",
		"dorință": "năzuință",
		"dorit": "tânjit",
		"dorm": "mă odihnesc",
		"dormea": "se odihnea",
		"dormi": "te odihnești",
		"dormim": "ne odihnim",
		"dormit": "se odihni",
		"dormitoare": "spații de odihnă",
		"dormitoarea": "spații de odihnăa",
		"dormitor": "spațiu de odihnă",
		"doua": "pereche",
		"douăzeci": "20 unități",
		"dragoste": "afecțiune",
		"dragostea": "afecțiunea",
		"dragosti": "afecțiuni",
		"drept": "prerogativă",
		"drepturi": "prerogative",
		"drum": "trecere",
		"drumuri": "treceri",
		"dulap": "garderobă",
		"dulce": "îndulcit",
		"dulcea": "îndulcita",
		"duminică": "ziua a șaptea a săptămânii",
		"durere": "suferință corporală",
		"durerea": "suferința corporală",
		"dureri": "suferințe corporale",
		"durerile": "suferințele corporale",
		"dușman": "adversar",
		"dușmani": "adversari",
		"dușmanii": "adversarii",
		"dușmanul": "adversarul",
		"dă": "oferi",
		"dădea": "oferea",
		"dăunător": "păgubitor",
		"ea": "dânsa",
		"economie": "sistem economic",
		"economiea": "sistem economica",
		"economii": "sisteme economice",
		"ecran": "afișaj",
		"ecranul": "afișajul",
		"ediție": "tipăritură",
		"edițiea": "tipăriturăa",
		"egal": "echivalent",
		"ei": "dânșii",
		"el": "dânsul",
		"ele": "dânsele",
		"elea": "dânselea",
		"elefant": "pachiderm uriaș",
		"elefantul": "pachidermul uriaș",
		"elev": "ucenic",
		"email": "poștă electronică",
		"emailul": "poșta electronică",
		"enciclopedia": "compendiul",
		"enciclopedie": "compendium",
		"epoca": "perioada istorică",
		"epocă": "perioadă istorică",
		"era": "se afla",
		"erau": "se aflau",
		"este": "exista",
		"estea": "exista",
		"eu": "subsemnatul",
		"evident": "manifest",
		"exact": "precis",
		"examen": "verificare",
		"examene": "verificări",
		"examenele": "verificările",
		"examenul": "verificarea",
		"exercițiu": "antrenament",
		"experiența": "competența",
		"experiență": "competență",
		"eșec": "ratare",
		"eșecul": "ratarea",
		"fac": "efectuează",
		"face": "efectua",
		"facea": "efectua",
		"faci": "efectuezi",
		"factura": "documentul de plată",
		"facturi": "documente de plată",
		"facturile": "documentele de plată",
		"factură": "document de plată",
		"facultate": "subdiviziune universitară",
		"facultatea": "subdiviziunea universitară",
		"fals": "fictiv",
		"falsa": "fictiva",
		"false": "fictive",
		"falsea": "fictivea",
		"falsă": "fictivă",
		"falși": "fictivi",
		"familia": "rudele",
		"familie": "rude",
		"familiea": "rudea",
		"familii": "rude",
		"familiile": "neamurile",
		"familiilea": "neamurilea",
		"farfuria": "vasul pentru mâncare",
		"farfurie": "vas pentru mâncare",
		"farmacie": "instituție farmaceutică",
		"farmaciea": "instituție farmaceuticăa",
		"fascinat": "captivat",
		"fascinează": "captivează",
		"fascinez": "captivez",
		"fata": "domnișoara",
		"fată": "domnișoară",
		"fața": "vizajul",
		"față": "vizaj",
		"febra": "starea febrilă",
		"februarie": "a doua lună a anului",
		"febră": "stare febrilă",
		"felicit": "complimentez",
		"felicitez": "complimentez",
		"felicită": "complimentează",
		"felicităm": "complimentăm",
		"femei": "doamne",
		"femeia": "doamna",
		"femeie": "doamnă",
		"femeiea": "doamnăa",
		"femeile": "doamnele",
		"femeilea": "doamnelea",
		"fereastra": "deschizătura",
		"fereastră": "deschizătură",
		"ferestre": "deschizături",
		"ferestrea": "deschizăturia",
		"fericit": "exuberant",
		"fericita": "vesela",
		"fericite": "exuberante",
		"fericitea": "veselea",
		"fericită": "exuberantă",
		"fericiți": "exuberanți",
		"fermier": "agricultor",
		"fete": "domnișoare",
		"fetea": "domnișoarea",
		"fetele": "domnișoarele",
		"fetelea": "domnișoarelea",
		"fețe": "vizaje",
		"fețea": "chipuria",
		"ficat": "organ de detoxifiere",
		"ficatul": "organul de detoxifiere",
		"fiica": "moștenitorul feminin",
		"fiică": "moștenitor feminin",
		"film": "cinematografie",
		"filme": "cinematografii",
		"filmea": "cinematografiia",
		"filozof": "gânditor",
		"filozofi": "gânditori",
		"final": "în cele din urmă",
		"fiu": "moștenitor masculin",
		"fiul": "moștenitorul masculin",
		"floare": "boboc",
		"floarea": "boboca",
		"flori": "boboci",
		"flămând": "famelic",
		"flămândă": "famelică",
		"foarte": "extrem de",
		"foartea": "extrem dea",
		"foc": "flacără",
		"focuri": "flăcări",
		"folosea": "utiliza",
		"folosesc": "utilizează",
		"folosește": "utiliza",
		"foloseștea": "utiliza",
		"folosit": "utilizat",
		"forma": "configurația",
		"formă": "configurație",
		"forța": "vigoare",
		"forțe": "vigori",
		"forțea": "vigoria",
		"forță": "vigoare",
		"fost": "existat",
		"fotoliu": "scaun confortabil",
		"fotoliul": "scaunul confortabil",
		"frate": "consanguin masculin",
		"fratea": "consanguina",
		"fratele": "consanguinul masculin",
		"frați": "consanguini",
		"frica": "teama",
		"frici": "temeri",
		"frică": "teamă",
		"frigider": "aparat răcitor",
		"frigiderul": "aparatul răcitor",
		"fruct": "rod",
		"frumoasa": "splendida",
		"frumoase": "splendide",
		"frumoasea": "splendidea",
		"frumoasă": "splendidă",
		"frumos": "splendid",
		"frumoși": "splendizi",
		"frumusețe": "splendoare",
		"frumusețea": "splendoarea",
		"frumuseți": "splendoare",
		"fulger": "scânteie cerească",
		"fur": "pradă",
		"furat": "prădat",
		"furculița": "ustensila cu dinți",
		"furculiță": "ustensilă cu dinți",
		"furie": "indignare",
		"furiea": "indignarea",
		"furii": "indignări",
		"furtuna": "uragan",
		"furtună": "uragan",
		"fură": "pradă",
		"fusta": "îmbrăcămintea feminină",
		"fustă": "îmbrăcăminte feminină",
		"făcea": "efectua",
		"făceam": "efectuam",
		"făceau": "efectuau",
		"făcut": "efectuat",
		"galben": "auriu",
		"galbena": "aurie",
		"galbene": "aurii",
		"galbenea": "auriia",
		"galbeni": "aurii",
		"galbenă": "aurie",
		"gara": "stație de tren",
		"gară": "stație de tren",
		"geanta": "sac de mâna",
		"geantă": "sac de mână",
		"geloasă": "invidioasă",
		"gelos": "invidios",
		"general": "căpetenie",
		"genunchi": "articulație femurală",
		"genunchiul": "articulația femurală",
		"ghete": "încălțăminte ușoară",
		"ghetele": "încălțămintea ușoară",
		"glorie": "renume",
		"gloriea": "renumea",
		"goala": "vacanta",
		"goale": "vacante",
		"goalea": "vacantea",
		"goală": "vacantă",
		"goi": "vacanți",
		"gol": "vacant",
		"grea": "anevoioasă",
		"grei": "anevoioși",
		"grele": "anevoioase",
		"grelea": "anevoioasea",
		"greu": "cu dificultate",
		"gri": "cenușiu",
		"gri-deschis": "cenușiu-pal",
		"grija": "preocupare",
		"grijă": "preocupare",
		"grindina": "căderi de gheața",
		"grindină": "căderi de gheață",
		"groasa": "densa",
		"groase": "dense",
		"groasea": "densea",
		"groasă": "densă",
		"gros": "dens",
		"groși": "denși",
		"grădina": "spațiu verde",
		"grădini": "spații verzi",
		"grădinița": "instituția preșcolară",
		"grădiniță": "instituție preșcolară",
		"grădină": "spațiu verde",
		"gura": "cavitatea orală",
		"guri": "cavități orale",
		"gură": "cavitate orală",
		"gust": "percepție gustativă",
		"gustul": "percepția gustativă",
		"guvernator": "administrator regional",
		"gând": "cugetare",
		"gândea": "chibzuia",
		"gândesc": "chibzuiesc",
		"gândește": "chibzui",
		"gândeștea": "chibzuia",
		"gândești": "chibzuiești",
		"gândim": "chibzuim",
		"gândit": "chibzuit",
		"gânduri": "cugetări",
		"gâsca": "pasărea acvatică mare",
		"gâscă": "pasăre acvatică mare",
		"gât": "regiune cervicală",
		"gâtul": "regiunea cervicală",
		"găina": "pasărea domestică",
		"găini": "păsări domestice",
		"găină": "pasăre domestică",
		"găsea": "descoperea",
		"găsesc": "descoperă",
		"găsește": "descoperi",
		"găseștea": "descoperia",
		"găsit": "descoperit",
		"hobby": "preocupare",
		"hobbyul": "preocuparea",
		"hotel": "loc de cazare",
		"hârtia": "celuloza",
		"hârtie": "celuloză",
		"hârtiea": "material de scrisa",
		"ia": "prelua",
		"ianuarie": "prima lună a anului",
		"iarba": "vegetație",
		"iarbă": "vegetație",
		"iarna": "anotimpul rece",
		"iarnă": "anotimp rece",
		"iartă": "absolvă",
		"iartăm": "absolvim",
		"iau": "preiau",
		"idee": "concept",
		"ideea": "concepta",
		"idei": "concepte",
		"identic": "același",
		"iepure": "leporid",
		"iepurele": "leporidul",
		"ieri": "ziua precedentă",
		"iert": "absolv",
		"iertare": "absolvire",
		"iertarea": "absolvirea",
		"iertat": "absolvit",
		"iertăm": "absolvim",
		"iertări": "absolvire",
		"ierți": "absolvi",
		"imaginar": "ficțional",
		"imediat": "neîntârziat",
		"important": "esențial",
		"importanta": "esențiala",
		"importante": "esențiale",
		"importantea": "esențialea",
		"importantă": "esențială",
		"importanți": "esențiali",
		"impozit": "obligație fiscală",
		"impozite": "obligații fiscale",
		"impozitele": "obligațiile fiscale",
		"impozitul": "obligația fiscală",
		"imprimanta": "dispozitivul de tipărire",
		"imprimantă": "dispozitiv de tipărire",
		"in": "țesătură de in",
		"inaudibil": "imperceptibil",
		"inegal": "disproporționat",
		"inginer": "constructor",
		"ingineri": "constructori",
		"inima": "organul cardiac",
		"inimi": "organe cardiace",
		"inimă": "organ cardiac",
		"interes": "fascinație",
		"interesant": "captivant",
		"interesanta": "captivanta",
		"interesante": "captivante",
		"interesantea": "captivantea",
		"interesantă": "captivantă",
		"interesanți": "captivanți",
		"interesul": "fascinația",
		"internațional": "mondial",
		"internet": "rețea globală",
		"internetul": "rețeaua globală",
		"inul": "țesătura de in",
		"inutil": "neavenit",
		"invizibil": "imperceptibil",
		"istorie": "cronică",
		"istoriea": "cronicăa",
		"istorii": "cronici",
		"iubea": "adora",
		"iubesc": "ador",
		"iubește": "adora",
		"iubeștea": "adora",
		"iubești": "adori",
		"iubim": "adorăm",
		"iubit": "adorat",
		"iulie": "a șaptea lună a anului",
		"iunie": "a șasea lună a anului",
		"jacheta": "haina exterioară",
		"jachetă": "haină exterioară",
		"jefuiesc": "spoliem",
		"jefuiește": "spoliază",
		"jefuit": "spoliat",
		"joaca": "distra",
		"joacă": "distra",
		"joasa": "coborâta",
		"joase": "coborâte",
		"joasea": "coborâtea",
		"joasă": "coborâtă",
		"joi": "ziua a patra a săptămânii",
		"jos": "în zona inferioară",
		"joși": "coborâți",
		"jucat": "se distra",
		"jur": "atest solemn",
		"jurat": "atestat solemn",
		"juri": "atestă solemn",
		"jură": "atestă solemn",
		"la dreapta": "spre dextrocentral",
		"la revedere": "rămas bun",
		"la stânga": "spre senestral",
		"lacăt": "dispozitiv de închidere",
		"lampa": "iluminatorul",
		"lampă": "iluminator",
		"lapte": "produs lactat lichid",
		"laptea": "produs lactat lichida",
		"laptop": "computer portabil",
		"laptopul": "computerul portabil",
		"lat": "amplu",
		"lata": "ampla",
		"late": "ample",
		"latea": "amplea",
		"lată": "amplă",
		"laud": "elogiez",
		"laudă": "elogiază",
		"lașitate": "timorare",
		"lașitatea": "timorarea",
		"lașități": "timorări",
		"lați": "ampli",
		"lecția": "instruirea",
		"lecție": "instruire",
		"lecțiea": "instruirea",
		"lecții": "instruiri",
		"lecțiile": "instruirile",
		"lege": "statut",
		"legea": "statuta",
		"legi": "statute",
		"leguma": "cultură horticola",
		"legumă": "cultură horticolă",
		"lei": "monede naționale",
		"lemn": "material lemnos",
		"lemnul": "materialul lemnos",
		"lent": "lin",
		"lenta": "lina",
		"lente": "line",
		"lentea": "linea",
		"lentă": "lină",
		"lenți": "lini",
		"leu": "moneda națională",
		"leul": "moneda națională",
		"liber": "independent",
		"libertate": "independență",
		"libertatea": "independențăa",
		"liceu": "instituție de învățământ secundar",
		"liceul": "instituția de învățământ secundar",
		"limba": "organul lingual",
		"limbi": "organe linguale",
		"limbă": "organ lingual",
		"lingura": "ustensila de mâncare",
		"linguri": "ustensile de mâncare",
		"lingură": "ustensilă de mâncare",
		"liniște": "tăcere",
		"liniștea": "tăcerea",
		"liniștit": "tăcut",
		"liniștita": "tăcuta",
		"liniștite": "tăcute",
		"liniștitea": "tăcutea",
		"liniștită": "tăcută",
		"liniștiți": "tăcuți",
		"loc": "locație",
		"locul": "locația",
		"locuri": "locații",
		"locurile": "locațiile",
		"locurilea": "locațiilea",
		"loialitate": "fidelitate",
		"loialitatea": "fidelitatea",
		"lor": "dânșilor",
		"lua": "prelua",
		"luat": "preluat",
		"lucra": "presta",
		"lucrat": "prestat",
		"lucreaza": "presta",
		"lucrează": "presta",
		"lucrez": "prestez",
		"lucrezi": "prestezi",
		"lucru": "obiect",
		"lucrul": "obiectul",
		"lucruri": "obiecte",
		"lucrurile": "obiectele",
		"lucrurilea": "obiectelea",
		"lucrăm": "prestăm",
		"lui": "dânsului",
		"lume": "univers",
		"lumea": "universa",
		"lumina": "iluminație",
		"lumini": "iluminații",
		"luminoasa": "radianta",
		"luminoase": "radiante",
		"luminoasea": "radiantea",
		"luminoasă": "radiantă",
		"luminos": "radiant",
		"luminoși": "radianți",
		"lumină": "iluminație",
		"luna": "perioada lunară",
		"lung": "extins",
		"lunga": "extinsa",
		"lungi": "extinse",
		"lungă": "extinsă",
		"luni": "ziua întâi a săptămânii",
		"lună": "perioadă lunară",
		"lup": "carnivor sălbatic",
		"lupi": "carnivori sălbatici",
		"lupt": "mă bat",
		"luptat": "bătut",
		"luptă": "se bate",
		"lupul": "carnivorul sălbatic",
		"lâna": "fibra animală",
		"lână": "fibră animală",
		"lămpi": "iluminatoare",
		"lămpile": "iluminatoarele",
		"lămâie": "citric acrișor",
		"lămâiea": "citric acrișora",
		"lăudat": "elogiat",
		"mai": "a cincea lună a anului",
		"mai bun": "superior",
		"mai bună": "superioară",
		"mai mare": "mai amplu",
		"mai mic": "diminuat",
		"mai rea": "inferioară",
		"mai rău": "inferior",
		"maimuța": "primatul",
		"maimuță": "primat",
		"mama": "părintele matern",
		"mame": "părinți materni",
		"mamă": "părinte matern",
		"manual": "instrument didactic",
		"manuale": "instrumente didactice",
		"manualele": "instrumentele didactice",
		"manualul": "instrumentul didactic",
		"mare": "considerabilă",
		"marea": "considerabilăa",
		"mari": "considerabile",
		"marinar": "navigator",
		"maro": "ciocolatiu",
		"maronie": "ciocolatie",
		"maroniea": "ciocolatiea",
		"maronii": "ciocolatii",
		"martie": "a treia lună a anului",
		"marți": "ziua a doua a săptămânii",
		"masa": "tabloul",
		"masă": "tablou",
		"mașina": "automobil",
		"mașini": "automobile",
		"mașină": "automobil",
		"mea": "a mea proprie",
		"medic": "doctor",
		"medicament": "preparat farmaceutic",
		"medicamente": "preparate farmaceutice",
		"medicamentele": "preparatele farmaceutice",
		"medicamentul": "preparatul farmaceutic",
		"medici": "doctori",
		"mereu": "în continuu",
		"merg": "se deplasează",
		"merge": "deplasa",
		"mergea": "se deplasa",
		"mergeau": "se deplasau",
		"mers": "se deplasa",
		"mesaj": "comunicare scrisă",
		"mesaje": "comunicări scrise",
		"mesajele": "comunicările scrise",
		"mesajul": "comunicarea scrisă",
		"mese": "tablouri",
		"mesea": "mobiliere de servita",
		"mesele": "tablourile",
		"metal": "aliaj",
		"metale": "aliaje",
		"metrou": "transport subteran",
		"meu": "al meu propriu",
		"mic": "redus",
		"mica": "redusa",
		"mici": "reduse",
		"mică": "redusă",
		"mie": "miliar",
		"miea": "miliara",
		"miercuri": "ziua a treia a săptămânii",
		"milenii": "milleniumuri",
		"milenniu": "milleniu",
		"milion": "un milion",
		"minciuna": "falsitate",
		"minciuni": "falsități",
		"minciună": "falsitate",
		"ministru": "membru al guvernului",
		"minte": "intelect",
		"mintea": "intelecta",
		"minut": "moment temporal",
		"minute": "intervale temporale",
		"minutea": "intervale temporalea",
		"minutul": "momentul temporal",
		"mirat": "uimit",
		"mirată": "uimită",
		"miros": "percepție olfactivă",
		"mirosul": "percepția olfactivă",
		"moare": "deceda",
		"moarea": "deceda",
		"moarte": "deces",
		"moartea": "decesa",
		"modern": "contemporan",
		"modest": "umil",
		"modeste": "umile",
		"modestă": "umilă",
		"modești": "umili",
		"moneda": "piesa de schimb",
		"monede": "piese financiare",
		"monedea": "piese financiarea",
		"monedă": "piesă de schimb",
		"monument": "edificiu comemorativ",
		"morcov": "rădăcinoasă",
		"mort": "neînsuflețit",
		"morți": "decese",
		"motocicleta": "vehicul motorizat cu două roți",
		"motocicletă": "vehicul motorizat cu două roți",
		"mouse": "dispozitiv indicator",
		"mult": "considerabil",
		"mulțumesc": "exprim recunoștință",
		"mulțumesc frumos": "îți mulțumesc cordial",
		"mulțumesc mult": "îmi exprim profunda recunoștință",
		"mulțumește": "exprimă recunoștință",
		"mulțumit": "satisfăcut",
		"mulțumită": "satisfăcută",
		"munca": "activitate",
		"muncea": "depunea efort",
		"muncesc": "depun efort",
		"muncește": "efort",
		"munceștea": "eforta",
		"muncești": "depui efort",
		"munci": "activități",
		"muncim": "depunem efort",
		"muncit": "depune efort",
		"muncitor": "lucrător",
		"muncă": "activitate",
		"munte": "înălțime",
		"muntea": "înălțimea",
		"munți": "înălțimi",
		"murdar": "soios",
		"murdara": "soioasa",
		"murdare": "soioase",
		"murdarea": "soioasea",
		"murdari": "soioși",
		"murdară": "soioasă",
		"murea": "deceda",
		"murit": "decedat",
		"muzeu": "loc de expoziție",
		"muzica": "compoziție",
		"muzici": "compoziții",
		"muzician": "interpret",
		"muzicieni": "interpreți",
		"muzică": "compoziție",
		"mâine": "ziua următoare",
		"mâinea": "ziua următoarea",
		"mâini": "membre superioare",
		"mâna": "membru superior",
		"mânca": "consuma",
		"mâncare": "alimente",
		"mâncarea": "alimentea",
		"mâncat": "consumat",
		"mâncăm": "consumăm",
		"mâncări": "alimente",
		"mândre": "demne",
		"mândresc": "îmi reflect mândria",
		"mândrește": "își reflect mândria",
		"mândri": "demni",
		"mândrit": "afișat mândrie",
		"mândru": "demn",
		"mândră": "demnă",
		"mână": "membru superior",
		"mănuși": "îmbrăcăminte pentru mâini",
		"mănușile": "îmbrăcămintea pentru mâini",
		"mănânc": "consum",
		"mănânca": "consuma",
		"mănânci": "consumi",
		"mănâncă": "consuma",
		"măr": "fruct de măr",
		"mări": "oceane",
		"mărime": "dimensiune",
		"mărimea": "dimensiunea",
		"mătase": "fibră naturală",
		"mătasea": "fibra naturală",
		"mătușa": "ruda maternă",
		"mătușă": "rudă maternă",
		"nas": "organ olfactiv",
		"nasul": "organul olfactiv",
		"nasuri": "rinioane",
		"național": "patriotic",
		"ne vedem": "ne vom revedea",
		"neagra": "ebena",
		"neagră": "ebenă",
		"necesar": "indispensabil",
		"neclar": "ambiguu",
		"necunoscut": "anonim",
		"nedelicios": "fad",
		"negre": "ebenă",
		"negrea": "ebenăa",
		"negri": "ebenă",
		"negru": "ebenă",
		"neimportant": "nesemnificativ",
		"nemulțumit": "nesatisfăcut",
		"nemulțumită": "nesatisfăcută",
		"neplăcut": "dezagreabil",
		"nepoata": "descendenta directă",
		"nepoată": "descendentă directă",
		"nepoliticoasa": "necuviincioasa",
		"nepoliticoase": "necuviincioase",
		"nepoliticoasea": "necuviincioasea",
		"nepoliticoasă": "necuviincioasă",
		"nepoliticos": "necuviincios",
		"nepoliticoși": "necuviincioși",
		"nepopular": "respins",
		"nepot": "descendent direct",
		"nepotul": "descendentul direct",
		"nervozitate": "agitație",
		"nervozitatea": "agitațiea",
		"nevinovat": "fără culpă",
		"nevinovată": "fără culpă",
		"nevoia": "necesitatea",
		"nevoie": "necesitate",
		"niciodata": "deloc",
		"niciodată": "în niciun moment",
		"nicăieri": "în niciun loc",
		"noapte": "perioadă nocturnă",
		"noapte bună": "noapte senină",
		"noaptea": "perioadă nocturnăa",
		"noi": "noi împreună",
		"noiembrie": "a unsprezecea lună a anului",
		"nopți": "perioade nocturne",
		"normal": "standard",
		"nota": "calificativul",
		"note": "calificative",
		"notele": "calificativele",
		"notă": "calificativ",
		"nou": "modern",
		"noua": "nonet",
		"nouă": "nonet",
		"nouăsprezece": "19 unități",
		"nouăzeci": "90 unități",
		"nu este așa": "nu este corect",
		"nu înțeleg": "nu sesizez",
		"nu știu": "nu sunt informat",
		"născut": "venit pe lume",
		"o mie": "miliar",
		"o sută": "centenar",
		"oaia": "ovina",
		"oaie": "ovină",
		"oala": "vasul de gătit",
		"oală": "vas de gătit",
		"oameni": "indivizi",
		"oameni de știință": "cercetători",
		"oamenii": "indivizii",
		"obișnuit": "convențional",
		"obligație": "îndatorire",
		"obligațiea": "îndatorirea",
		"obligații": "îndatoriri",
		"obosit": "epuizat",
		"obosita": "epuizata",
		"obosite": "epuizate",
		"obositea": "epuizatea",
		"obosită": "epuizată",
		"obosiți": "epuizați",
		"ochelari": "lentile optice",
		"ochi": "organ vizual",
		"ochii": "organele vizuale",
		"ochiul": "privirea",
		"octombrie": "a zecea lună a anului",
		"ocupat": "preocupat",
		"odihnit": "refăcut",
		"odihnita": "refăcuta",
		"odihnite": "refăcute",
		"odihnitea": "refăcutea",
		"odihnită": "refăcută",
		"odihniți": "refăcuți",
		"ofera": "furniza",
		"oferit": "furnizat",
		"oferă": "furniza",
		"ofițer": "comandant",
		"oi": "ovine",
		"om": "individ",
		"om de știință": "cercetător",
		"omul": "individul",
		"onoare": "demnitate",
		"onoarea": "demnitatea",
		"operația": "intervenția chirurgicală",
		"operație": "intervenție chirurgicală",
		"operații": "intervenții chirurgicale",
		"operațiile": "intervențiile chirurgicale",
		"opt": "octet",
		"optsprezece": "18 unități",
		"optzeci": "80 unități",
		"ora": "perioada orară",
		"oraș": "metropolă",
		"orașe": "metropole",
		"orașea": "metropolea",
		"orașele": "metropolele",
		"orașelea": "metropolelea",
		"orașul": "metropola",
		"ore": "perioade orare",
		"orea": "perioade orarea",
		"oră": "perioadă orară",
		"ospătar": "deservant",
		"ou": "produs ovipar",
		"pace": "armonie",
		"pacea": "armoniea",
		"pahar": "recipient pentru lichide",
		"paharul": "recipientul pentru lichide",
		"paisprezece": "14 unități",
		"palton": "manta",
		"paltonul": "mantaua",
		"pantaloni": "veșminte inferioare",
		"pantalonii": "veșmintele inferioare",
		"pantofi": "încălțăminte",
		"pantofii": "încălțămintea",
		"para": "fruct de păr",
		"parc": "zonă verde",
		"parcuri": "zone verzi",
		"pară": "fruct de păr",
		"parțial": "fragmentar",
		"pasiune": "ardoare",
		"pasiunea": "ardoarea",
		"pastila": "preparatul solid",
		"pastile": "preparate solide",
		"pastilele": "preparatele solide",
		"pastilă": "preparat solid",
		"pasăre": "zburătoare",
		"pasărea": "zburătoarea",
		"pat": "loc de odihnă",
		"patru": "cvartet",
		"patruzeci": "40 unități",
		"patul": "locul de odihnă",
		"paturi": "locuri de odihnă",
		"paznic": "străjer",
		"pe curând": "pe curând să ne revedem",
		"pedepsesc": "sancționez",
		"pedepsește": "sancționează",
		"pedepsit": "sancționat",
		"perete": "delimitator vertical",
		"peretea": "delimitator verticala",
		"pereți": "delimitatori verticali",
		"pericol": "primejdie",
		"periculos": "primejdios",
		"peste tot": "pretutindeni",
		"pește": "creatură acvatică",
		"peștea": "ihtiofaunăa",
		"peștele": "creatura acvatică",
		"piatra": "roca",
		"piatră": "rocă",
		"picioare": "membre inferioare",
		"picioarea": "membre inferioarea",
		"picior": "membru inferior",
		"piciorul": "membrul inferior",
		"piele": "epidermă",
		"pielea": "epiderma",
		"piept": "torace",
		"pieptul": "toracele",
		"pierd": "ratăc",
		"pierde": "ratează",
		"pierdut": "ratat",
		"pietre": "roci",
		"pilot": "aviator",
		"piper": "condiment iute",
		"pisica": "felin",
		"pisici": "feline",
		"pisică": "felin",
		"pix": "instrument de scris",
		"plan": "strategie",
		"planuri": "strategii",
		"plastic": "material sintetic",
		"plasticul": "materialul sintetic",
		"pleaca": "îndepărta",
		"pleacă": "îndepărta",
		"pleca": "se îndepărta",
		"plecat": "se îndepărta",
		"plictisesc": "obosesc",
		"plictisește": "obosește",
		"plictisit": "obosit",
		"plictisitoare": "monotone",
		"plictisitoarea": "monotonea",
		"plictisitor": "monoton",
		"plictisitori": "monotoni",
		"plin": "îmbelșugat",
		"plina": "îmbelșugata",
		"pline": "îmbelșugate",
		"plinea": "îmbelșugatea",
		"plini": "îmbelșugați",
		"plină": "îmbelșugată",
		"plâng": "lăcrimez",
		"plângem": "lăcrimăm",
		"plângi": "lăcrimezi",
		"plăcere": "delectare",
		"plăcerea": "delectarea",
		"plăcut": "agreabil",
		"plămâni": "organe respiratorii",
		"plămânii": "organele respiratorii",
		"plătește": "remunera",
		"plăteștea": "remunera",
		"plătit": "remunerat",
		"poate": "eventual",
		"poatea": "eventuala",
		"podea": "sol interior",
		"podele": "soluri interioare",
		"podelea": "soluri interioarea",
		"poet": "rapsod",
		"politica": "guvernare",
		"politici": "guvernări",
		"politicos": "amabil",
		"politică": "guvernare",
		"polițist": "agent al ordinii",
		"popular": "preferat",
		"porc": "porcină",
		"porci": "porcine",
		"porcul": "porcina",
		"port": "port maritim",
		"portocala": "fruct citric",
		"portocalie": "oranj",
		"portocaliea": "oranja",
		"portocalii": "oranj",
		"portocaliu": "oranj",
		"portocală": "fruct citric",
		"portofel": "buzunar de bani",
		"pot": "sunt capabil",
		"poșta": "oficiu poștal",
		"poștă": "oficiu poștal",
		"poți": "ești capabil",
		"predat": "capitulat",
		"predau": "capitulez",
		"predă": "capitulează",
		"preot": "duhovnic",
		"președinte": "șef de stat",
		"președintea": "șef de stata",
		"preț": "valoare monetară",
		"prețul": "valoarea monetară",
		"prețuri": "valori monetare",
		"prețurile": "valorile monetare",
		"prieten": "tovarăș",
		"prieteni": "tovarăși",
		"prietenie": "camaraderie",
		"prieteniea": "camaraderiea",
		"prietenii": "tovarășii",
		"prietenul": "tovarășul",
		"prima": "inițiala",
		"primar": "edil",
		"primește": "obține",
		"primeștea": "obținea",
		"primit": "obținet",
		"primitiv": "barbar",
		"primul": "inițialul",
		"primăvara": "anotimpul de revigorare",
		"primăvară": "anotimp de revigorare",
		"prinț": "moștenitor",
		"prințesa": "moștenitoare",
		"prințesă": "moștenitoare",
		"privat": "confidențial",
		"privea": "contempla",
		"privesc": "contemplu",
		"privește": "contempla",
		"priveștea": "contempla",
		"privești": "contemplezi",
		"privim": "contemplăm",
		"privit": "contemplat",
		"proasta": "neghioaba",
		"proaste": "obtuze",
		"proastea": "neghioabea",
		"proastă": "obtuză",
		"problema": "dilema",
		"probleme": "dileme",
		"problemea": "dilemea",
		"problemă": "dilemă",
		"profesor": "educator",
		"profesori": "educatori",
		"promis": "făgăduit",
		"promit": "făgăduiesc",
		"promite": "făgăduiește",
		"promitem": "făgăduim",
		"promiți": "făgăduiești",
		"prost": "obtuz",
		"prostie": "obtuzitate",
		"prostiea": "obtuzitatea",
		"prostii": "obtuzități",
		"proști": "obtuzi",
		"prânz": "perioadă meridiană",
		"prânzuri": "perioade meridiane",
		"public": "deschis",
		"pui": "pasăre comestibilă",
		"putem": "suntem capabili",
		"putere": "autoritate",
		"puterea": "autoritatea",
		"puternic": "robust",
		"puternica": "robusta",
		"puternice": "robuste",
		"puternicea": "robustea",
		"puternici": "robuști",
		"puternică": "robustă",
		"puțin": "minim",
		"pâine": "produs de panificație",
		"pâinea": "produs de panificațiea",
		"păci": "armonii",
		"pădure": "codru",
		"pădurea": "codrua",
		"păduri": "codri",
		"pălăria": "cilindrul",
		"pălărie": "cilindru",
		"părinți": "progenitori",
		"păsări": "zburătoare",
		"radio": "dispozitiv auditiv",
		"radiouri": "dispozitive auditive",
		"raft": "stelaj",
		"rana": "vătămarea corporală",
		"rană": "vătămare corporală",
		"rapid": "iute",
		"rapida": "iute",
		"rapide": "iuți",
		"rapidea": "iuția",
		"rapidă": "iute",
		"rapizi": "iuți",
		"rar": "rareori",
		"rareori": "cu frecvență mică",
		"rața": "pasărea acvatică",
		"rață": "pasăre acvatică",
		"rea": "deficientă",
		"real": "tangibil",
		"rece": "glacială",
		"recea": "glacialăa",
		"reci": "glaciale",
		"rege": "monarh",
		"regea": "monarha",
		"regina": "monarhia",
		"regină": "monarhia",
		"regizor": "regizator",
		"regret": "deplâng",
		"regretat": "deplâns",
		"regretă": "deplânge",
		"rele": "deficiente",
		"relea": "deficientea",
		"religie": "credință",
		"religiea": "credințăa",
		"religii": "credințe",
		"repara": "restaura",
		"reparat": "restaurat",
		"repară": "restaura",
		"repede": "iute",
		"repedea": "iutea",
		"respect": "venerez",
		"respectat": "venerat",
		"respectă": "venerează",
		"respectăm": "venerăm",
		"respecți": "venerezi",
		"restaurant": "loc de servire a mesei",
		"revista": "magazin literar",
		"reviste": "magazine literare",
		"revistea": "magazine literarea",
		"revistă": "magazin literar",
		"rezultat": "consecință",
		"rezultate": "consecințe",
		"rezultatea": "consecințea",
		"rinichi": "organ excretor",
		"rinichii": "organele excretoare",
		"roagă": "imploră",
		"rochia": "ținuta elegantă",
		"rochie": "ținută elegantă",
		"rog": "implor",
		"rogi": "implori",
		"rol": "funcție",
		"roluri": "funcții",
		"roz": "trandafiriu",
		"roz-pal": "trandafiriu-pal",
		"roșie": "stacojie",
		"roșiea": "stacojiea",
		"roșii": "stacojii",
		"roșu": "stacojiu",
		"roșu-aprins": "purpuriu",
		"rugat": "implorat",
		"rugăm": "implorăm",
		"rural": "campestru",
		"rușinat": "stânjenit",
		"rușinată": "stânjenită",
		"rușine": "umilință",
		"rușinea": "umilințăa",
		"rușinează": "stânjenește",
		"rușinez": "stânjenesc",
		"râd": "hohotesc",
		"râdem": "hohotim",
		"râu": "curs de apă",
		"râuri": "cursuri de apă",
		"râzi": "hohotești",
		"răi": "deficienți",
		"răni": "vătămări corporale",
		"rănile": "vătămările corporale",
		"răsplătesc": "recompensez",
		"răsplătește": "recompensează",
		"răsplătit": "recompensat",
		"răspund": "replică",
		"răspunde": "replica",
		"răspundea": "replica",
		"răspuns": "replică",
		"răspunsuri": "replici",
		"rău": "viciu",
		"răutăcioasa": "malițioasa",
		"răutăcioase": "malițioase",
		"răutăcioasea": "malițioasea",
		"răutăcioasă": "malițioasă",
		"răutăcios": "malițios",
		"răutăcioși": "malițioși",
		"războaie": "conflicte armate",
		"războaiea": "conflicte armatea",
		"război": "conflict armat",
		"salarii": "remunerații",
		"salariile": "remunerațiile",
		"salariu": "remunerație",
		"salariul": "remunerația",
		"salut": "îmi exprim salutul",
		"salută": "se înclină",
		"salutăm": "ne înclinăm",
		"saluți": "îți exprimi salutul",
		"sare": "condiment salin",
		"sarea": "condiment salina",
		"sat": "așezare",
		"sate": "așezări",
		"satea": "așezăria",
		"scaner": "dispozitiv de scanare",
		"scanerul": "dispozitivul de scanare",
		"scaun": "mobilier",
		"scaune": "mobilier",
		"scaunea": "locuri de șezuta",
		"scaunele": "mobilierul",
		"scaunul": "mobilierul",
		"schimba": "modifica",
		"schimbat": "modificat",
		"schimbă": "modifica",
		"sclavie": "robie",
		"sclaviea": "robiea",
		"scop": "obiectiv",
		"scopuri": "obiective",
		"scria": "redacta",
		"scrie": "redacta",
		"scriea": "redacta",
		"scriem": "redactăm",
		"scrii": "redactezi",
		"scriitor": "autor",
		"scriitori": "autori",
		"scris": "redactat",
		"scrisoare": "epistolă",
		"scrisoarea": "epistolăa",
		"scrisori": "epistole",
		"scriu": "redactez",
		"scund": "coborât",
		"scunda": "coborâta",
		"scunde": "coborâte",
		"scundea": "coborâtea",
		"scundă": "coborâtă",
		"scunzi": "coborâți",
		"scurt": "abreviat",
		"scurta": "abreviata",
		"scurte": "abreviate",
		"scurtea": "abreviatea",
		"scurtă": "abreviată",
		"scurți": "abreviați",
		"scuze": "îmi cer scuze",
		"se naște": "vine pe lume",
		"se năștea": "venea pe lume",
		"seara": "amurg vesperal",
		"seară": "amurg vesperal",
		"secol": "centenar",
		"secole": "centenare",
		"secolea": "centenarea",
		"secolul": "centenarul",
		"secunda": "momentul infinitezimal",
		"secunde": "momente infinitezimale",
		"secundea": "momente infinitezimalea",
		"secundă": "moment infinitezimal",
		"separat": "în mod individual",
		"septembrie": "a noua lună a anului",
		"seri": "amurguri vesperale",
		"sigur": "neîndoielnic",
		"siguranța": "securitate",
		"siguranță": "securitate",
		"similar": "analog",
		"simpla": "elementara",
		"simple": "elementare",
		"simplea": "elementarea",
		"simpli": "elementari",
		"simplu": "elementar",
		"simplă": "elementară",
		"sincer": "candid",
		"site": "portal web",
		"siteul": "portalul web",
		"slab": "fragil",
		"slaba": "fragila",
		"slabe": "fragile",
		"slabea": "fragilea",
		"slabi": "fragili",
		"slabă": "fragilă",
		"slăbiciune": "fragilitate",
		"slăbiciunea": "fragilitatea",
		"slăbiciuni": "fragilități",
		"soare": "astru",
		"soarea": "astrua",
		"soba": "instalația de încălzire",
		"sobe": "instalații de încălzire",
		"sobă": "instalație de încălzire",
		"societate": "comunitate",
		"societatea": "comunitatea",
		"societăți": "comunități",
		"soldat": "militar",
		"soldați": "militari",
		"soluție": "rezolvare",
		"soluțiea": "rezolvarea",
		"soluții": "rezolvări",
		"sora": "consanguinul feminin",
		"sori": "aștri",
		"soră": "consanguin feminin",
		"soț": "partener marital",
		"soția": "partenera maritală",
		"soție": "parteneră maritală",
		"soțul": "partenerul marital",
		"spate": "regiune dorsală",
		"spatele": "regiunea dorsală",
		"special": "distinctiv",
		"speranța": "năzuința",
		"speranțe": "năzuințe",
		"speranțea": "năzuințea",
		"speranță": "năzuință",
		"speriat": "înfricoșat",
		"speriată": "înfricoșată",
		"sperie": "înfricoșează",
		"sperii": "înfricoșez",
		"spital": "instituție medicală",
		"sportiv": "atlet",
		"sportivi": "atleți",
		"spui": "comunici",
		"spun": "comunic",
		"spune": "comunica",
		"spunea": "comunica",
		"spuneau": "comunicau",
		"spunem": "comunicăm",
		"spus": "comunicat",
		"sta": "afla",
		"stadion": "arenă sportivă",
		"stat": "se afla",
		"statuie": "sculptură",
		"statuiea": "sculpturăa",
		"stau": "se află",
		"stație": "punct de oprire",
		"stațiea": "punct de oprirea",
		"stea": "astru",
		"stele": "aștri",
		"stelea": "aștria",
		"sticla": "materialul transparent",
		"sticlă": "material transparent",
		"strada": "artera",
		"stradă": "arteră",
		"strica": "distrugea",
		"stricat": "distruget",
		"strică": "distruge",
		"strig": "vociferez",
		"strigi": "vociferezi",
		"strigăm": "vociferăm",
		"strugure": "fruct de viță",
		"strugurea": "fruct de vițăa",
		"străzi": "artere",
		"student": "pupil",
		"studenți": "pupili",
		"stă": "afla",
		"stătea": "se afla",
		"subapreciat": "minimalizat",
		"subapreciază": "minimalizează",
		"subapreciez": "minimalizez",
		"subțire": "fină",
		"subțirea": "finăa",
		"subțiri": "fine",
		"succes": "triumf",
		"succesul": "triumful",
		"suflet": "psiche",
		"sunet": "vibrație acustică",
		"sunetul": "vibrația acustică",
		"sunt": "se găsesc",
		"supraestimat": "exagerat",
		"supraestimează": "exagerează",
		"supraestimez": "exagerez",
		"supărat": "iritat",
		"supărata": "iritata",
		"supărate": "iritate",
		"supăratea": "iritatea",
		"supărată": "iritată",
		"supărați": "iritați",
		"surori": "consanguine",
		"surprind": "uimesc",
		"surprinde": "uimește",
		"surprins": "uimit",
		"sus": "în zona superioară",
		"suta": "centenar",
		"sută": "centenar",
		"sâmbătă": "ziua a șasea a săptămânii",
		"sănătate": "stare de bine fizic",
		"sănătatea": "starea de bine fizic",
		"sănătoasa": "viguroasa",
		"sănătoase": "viguroase",
		"sănătoasea": "viguroasea",
		"sănătoasă": "viguroasă",
		"sănătos": "viguros",
		"sănătoși": "viguroși",
		"săptămâna": "septeniumul",
		"săptămâni": "septenniumuri",
		"săptămână": "septennium",
		"sărac": "nevoiaș",
		"săraca": "nevoiașa",
		"sărace": "nevoiașe",
		"săracea": "nevoiașea",
		"săraci": "nevoiași",
		"săracă": "nevoiașă",
		"sărat": "salin",
		"sărăcia": "lipsurile",
		"sărăcie": "lipsuri",
		"sătul": "saturat",
		"sătulă": "saturată",
		"ta": "a ta proprie",
		"tableta": "computerul cu ecran tactil",
		"tabletă": "computer cu ecran tactil",
		"tablou": "pictură",
		"tac": "păstrez tăcerea",
		"taci": "păstrezi tăcerea",
		"tandrețe": "duioșie",
		"tandrețea": "duioșiea",
		"tare": "intens",
		"tarea": "intensa",
		"tastatura": "dispozitivul de intrare",
		"tastatură": "dispozitiv de intrare",
		"tata": "părinte",
		"tată": "părinte patern",
		"tatăl": "părintele patern",
		"tavan": "acoperire superioară",
		"tavane": "acoperiri superioare",
		"tavanea": "acoperiri superioarea",
		"taxi": "vehicul de transport individual",
		"tați": "părinți paterni",
		"te rog": "îți solicit",
		"te rog frumos": "îți solicit cu respect",
		"teatru": "loc de spectacole",
		"telefoane": "dispozitive de comunicare",
		"telefoanea": "dispozitive de comunicarea",
		"telefoanele": "dispozitivele de comunicare",
		"telefon": "dispozitiv de comunicare",
		"telefonul": "dispozitivul de comunicare",
		"televizoare": "dispozitive vizuale",
		"televizoarea": "dispozitive vizualea",
		"televizor": "dispozitiv vizual",
		"tema": "sarcina",
		"temperatura": "indicatorul termometric",
		"temperatură": "indicator termometric",
		"temă": "sarcină",
		"termin": "finalizez",
		"termina": "finaliza",
		"terminat": "finalizat",
		"termină": "finaliza",
		"test": "evaluare",
		"teste": "evaluări",
		"testele": "evaluările",
		"testul": "evaluarea",
		"tigaia": "tava de gătit",
		"tigaie": "tavă de gătit",
		"tigru": "felin dungat",
		"tigrul": "felinul dungat",
		"timid": "sfios",
		"timide": "sfioase",
		"timidă": "sfioasă",
		"timizi": "sfioși",
		"timp": "moment",
		"timpul": "momentul",
		"timpuri": "momente",
		"timpurile": "momentele",
		"timpurilea": "momentelea",
		"tinere": "juvenile",
		"tinerea": "juvenilea",
		"tineri": "juvenili",
		"toamna": "anotimpul de tranziție",
		"toamnă": "anotimp de tranziție",
		"totul bine": "totul în ordine",
		"tramvai": "vehicul cu șine",
		"tratament": "terapie medicală",
		"tratamente": "terapii medicale",
		"tratamentele": "terapiile medicale",
		"tratamentul": "terapia medicală",
		"trebuiau": "erau necesare",
		"trebuie": "este necesar",
		"trei": "trio",
		"treisprezece": "13 unități",
		"treizeci": "30 unități",
		"tren": "convoi feroviar",
		"treptat": "etapizat",
		"trezit": "deșteptat",
		"trezită": "deșteptată",
		"trist": "melancolic",
		"trista": "îndurerata",
		"triste": "melancolice",
		"tristea": "îndureratea",
		"tristețe": "melancolie",
		"tristețea": "melancoliea",
		"tristeți": "melancolii",
		"tristă": "melancolică",
		"triști": "melancolici",
		"trădare": "perfidiate",
		"trădarea": "perfidiatea",
		"trăia": "viețuia",
		"trăiesc": "viețuiesc",
		"trăiește": "viețui",
		"trăieștea": "viețuia",
		"trăiești": "viețuiești",
		"trăim": "viețuim",
		"trăit": "viețuit",
		"tu": "dumneata",
		"tunet": "bubuit ceresc",
		"tuse": "simptom respirator",
		"tusea": "simptomul respirator",
		"tânăr": "juvenil",
		"tânăra": "juvenila",
		"tânără": "juvenilă",
		"târziu": "ulterior",
		"tău": "al tău propriu",
		"ud": "umed",
		"uimit": "stupefiat",
		"uimită": "stupefiată",
		"umeri": "articulații",
		"umăr": "articulație",
		"umărul": "articulația",
		"unchi": "rudă paternă",
		"unchiul": "ruda paternă",
		"uneori": "în mod ocazional",
		"universitate": "instituție de învățământ superior",
		"universitatea": "instituția de învățământ superior",
		"unsprezece": "11 unități",
		"unt": "produs gras",
		"unu": "singular",
		"ura": "ostilitate",
		"uragan": "ciclon tropical",
		"urban": "citadin",
		"ureche": "organ auditiv",
		"urechea": "organul auditiv",
		"urechi": "organe auditive",
		"uri": "ostilități",
		"urmaș": "succesor",
		"urmași": "succesori",
		"urs": "carnivor mare",
		"ursul": "carnivorul mare",
		"urâm": "detestăm",
		"urât": "respingător",
		"urâta": "respingătoare",
		"urâte": "respingătoare",
		"urâtea": "respingătoarea",
		"urâtă": "respingătoare",
		"urâțenia": "respingerea",
		"urâțenie": "respingere",
		"urâțeniea": "respingerea",
		"urâțenii": "respingere",
		"urâți": "respingători",
		"ură": "ostilitate",
		"urăsc": "detest",
		"urăște": "detesta",
		"urăștea": "detesta",
		"urăști": "detești",
		"urși": "carnivori mari",
		"uscat": "arid",
		"usturoi": "condiment aromatic",
		"util": "folositor",
		"ușa": "intrare",
		"uși": "intrări",
		"ușoara": "facila",
		"ușoare": "facile",
		"ușoarea": "facilea",
		"ușoară": "facilă",
		"ușor": "fără efort",
		"ușori": "facili",
		"ușă": "intrare",
		"vaca": "bovina",
		"vaccin": "imunizare",
		"vaccinul": "imunizarea",
		"vaci": "bovine",
		"vacă": "bovină",
		"vapor": "navă",
		"vara": "anotimpul călduros",
		"variat": "divers",
		"varza": "crucifere",
		"varză": "crucifere",
		"vară": "anotimp călduros",
		"vase": "ustensile",
		"vasul": "ustensila",
		"veche": "antică",
		"vechea": "anticăa",
		"vechi": "antice",
		"vede": "observa",
		"vedea": "observa",
		"vedeau": "observau",
		"venea": "sosea",
		"venit": "sosit",
		"verde": "smarald",
		"verde-deschis": "verde-pal",
		"verdea": "smaralda",
		"verita": "autentic",
		"verișor": "rudă colaterală",
		"verișorul": "ruda colaterală",
		"verzi": "smaralde",
		"vesel": "jovial",
		"vesela": "veselă-joviala",
		"vesele": "joviale",
		"veselea": "vesele-jovialea",
		"veseli": "joviali",
		"veselă": "jovială",
		"veverița": "rozătoarea",
		"veveriță": "rozătoare",
		"viața": "existența",
		"viață": "existență",
		"victorie": "triumf",
		"victoriea": "triumfa",
		"victorii": "triumfuri",
		"vieți": "existențe",
		"vin": "sosesc",
		"vina": "culpabilitate",
		"vinde": "tranzacționa",
		"vindea": "comercializa",
		"vine": "sosi",
		"vinea": "sosia",
		"vineri": "ziua a cincea a săptămânii",
		"vinovat": "culpabil",
		"vinovată": "culpabilă",
		"vinovăție": "culpabilitate",
		"vinovățiea": "culpabilitatea",
		"vinovății": "culpabilități",
		"vină": "culpabilitate",
		"violet": "purpuriu",
		"violeta": "purpurie",
		"violete": "purpurii",
		"violetea": "purpuriia",
		"violetă": "purpurie",
		"violeți": "purpurii",
		"vis": "reverie",
		"vise": "reverii",
		"visea": "reveriia",
		"viu": "însuflețit",
		"vizibil": "perceptibil",
		"voi": "dumneavoastră",
		"voia": "aspira",
		"voiau": "aspirau",
		"voința": "determinare",
		"voință": "determinare",
		"vor": "aspiră",
		"vorbesc": "comunic verbal",
		"vorbește": "comunica",
		"vorbeștea": "comunica",
		"vorbești": "comunici verbal",
		"vorbim": "comunicăm",
		"vorbit": "comunicat",
		"vrea": "aspira",
		"vreau": "aspir",
		"vrei": "aspiri",
		"vrem": "aspirăm",
		"vreme": "condiții meteorologice",
		"vremea": "condiții meteorologicea",
		"vrut": "aspirat",
		"vulpe": "carnivor viclean",
		"vulpea": "carnivorul viclean",
		"vând": "comercializează",
		"vândut": "tranzacționat",
		"vânt": "curent de aer",
		"vânzător": "comerciant",
		"vă rog": "vă solicit",
		"vă rog frumos": "vă solicit cu respect",
		"văd": "observă",
		"văzut": "observat",
		"zahăr": "îndulcitor",
		"zece": "decadă",
		"zecea": "decăa",
		"zero": "nimic",
		"zgomot": "vacarm",
		"zgomotoasa": "asurzitoare",
		"zgomotoase": "asurzitoare",
		"zgomotoasea": "asurzitoarea",
		"zgomotoasă": "asurzitoare",
		"zgomotos": "asurzitor",
		"zgomotoși": "asurzitori",
		"zi": "perioadă diurnă",
		"ziar": "publicație periodică",
		"ziare": "publicații periodice",
		"ziarea": "publicații periodicea",
		"zic": "declară",
		"zice": "declară",
		"zicea": "declara",
		"zile": "perioade diurne",
		"zilea": "perioade diurnea",
		"zis": "declarat",
		"ziua": "perioada diurnă",
		"zâmbesc": "schițez un surâs",
		"zâmbești": "schițezi un surâs",
		"îi place": "îi este pe plac",
		"îmbrăcăminte": "vesmânt",
		"îmi cer scuze": "îmi exprim căința",
		"îmi pare": "îmi se pare",
		"îmi pare rău": "îmi exprim regretul",
		"îmi place": "îmi este pe plac",
		"împiedic": "obstrucționez",
		"împiedicat": "obstrucționat",
		"împiedică": "obstrucționează",
		"împreuna": "în mod colectiv",
		"împreună": "în comun",
		"înainte": "anterior pe direcție",
		"înaintea": "anterior pe direcțiea",
		"înalt": "ridicat",
		"înalta": "ridicata",
		"înalte": "ridicate",
		"înaltea": "ridicatea",
		"înaltă": "ridicată",
		"înalți": "ridicați",
		"înapoi": "ulterior pe direcție",
		"înca": "în continuare",
		"încearca": "strădui",
		"încearcă": "strădui",
		"încep": "inițiază",
		"începe": "iniția",
		"începea": "iniția",
		"început": "inițiat",
		"încerca": "se strădui",
		"încercat": "se strădui",
		"încet": "lent",
		"închide": "sigila",
		"închidea": "sigila",
		"închis": "sigilat",
		"încred": "mă bizui",
		"încrede": "se bizuie",
		"încă": "în continuare",
		"îndoiesc": "ezit",
		"îndoiește": "ezită",
		"îndoiești": "eziți",
		"îndoim": "ezităm",
		"îndoit": "ezitat",
		"îndrăgostit": "atras erotic",
		"îndrăgostită": "atrasă erotic",
		"înfrângere": "eșec",
		"înfrângerea": "eșeca",
		"înfrângeri": "eșecuri",
		"îngrijorat": "preocupat",
		"îngrijorată": "preocupată",
		"îngust": "limitat",
		"îngusta": "limitata",
		"înguste": "limitate",
		"îngustea": "limitatea",
		"îngustă": "limitată",
		"înguști": "limitați",
		"însetat": "deshidratat",
		"însetată": "deshidratată",
		"întotdeauna": "perpetuu",
		"întreaba": "interoga",
		"întreabă": "interoga",
		"întreb": "interoghez",
		"întreba": "interoga",
		"întrebare": "interogație",
		"întrebarea": "interogațiea",
		"întrebat": "interogat",
		"întrebări": "interogații",
		"întunecat": "obscur",
		"întunecata": "obscura",
		"întunecate": "obscure",
		"întunecatea": "obscurea",
		"întunecată": "obscură",
		"întunecați": "obscuri",
		"întuneric": "obscuritate",
		"învața": "studia",
		"învață": "studia",
		"învețe": "să studieze",
		"învețea": "să studiezea",
		"înving": "trumf",
		"învinge": "triumfă",
		"învins": "triumfat",
		"învăț": "studiez",
		"învăța": "studia",
		"învățat": "studiat",
		"învățăm": "studiem",
		"înăuntru": "în interior",
		"înșală": "decepe",
		"înșel": "decep",
		"înșelat": "deceput",
		"înțeleg": "sesizează",
		"înțelege": "sesiza",
		"înțelegea": "sesiza",
		"înțelepciune": "sagacitate",
		"înțelepciunea": "sagacitatea",
		"înțelepciuni": "sagacități",
		"înțeles": "sesizat",
		"îți pare": "îți se pare",
		"șaisprezece": "16 unități",
		"șaizeci": "60 unități",
		"șapte": "septet",
		"șaptea": "septeta",
		"șaptesprezece": "17 unități",
		"șaptezeci": "70 unități",
		"șarpe": "reptilă",
		"șarpele": "reptila",
		"șase": "sextet",
		"șasea": "sexteta",
		"școala": "instituția de învățământ",
		"școală": "instituție de învățământ",
		"școli": "instituții",
		"șoarece": "rozătoare mică",
		"șoarecele": "rozătoarea mică",
		"șofer": "conducător auto",
		"șoptesc": "murmur",
		"șoptești": "murmuri",
		"șoptim": "murmurăm",
		"știa": "cunoștea",
		"știau": "cunoșteau",
		"știe": "cunoaște",
		"știea": "cunoaștea",
		"știința": "disciplina",
		"științe": "discipline",
		"științea": "disciplinea",
		"știință": "disciplină",
		"știu": "cunosc",
		"știut": "cunoaștet",
		"țara": "statul",
		"țară": "stat",
		"țesătura": "materialul textil",
		"țesătură": "material textil",
		"ție": "dumitale",
		"ținta": "obiectivul",
		"țintă": "obiectiv",
		"țăran": "agricultor",
		"țări": "state",
		"țările": "statele",
		"țărilea": "statelea",
	},
	Filler:   map[string]string{},
	Upgrades: map[string]string{},
}
