#!/usr/bin/env python3
"""
ULTIMATE expansion for all 3 dictionaries.
Goal: Push EN > 10000, RU > 8000, MO > 4000
"""
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DICT_DIR = PROJECT_ROOT / "internal" / "humanize"


def extract_existing(path: Path) -> dict:
    if not path.exists():
        return {}
    content = path.read_text(encoding='utf-8')
    pattern = r'"([^"]+)":\s*"([^"]+)"'
    matches = re.findall(pattern, content)
    return {k: v for k, v in matches}


def write_dict(path: Path, var_name: str, comment: str, entries: dict):
    sorted_items = sorted(entries.items())
    lines = [f"package humanize", "", comment, f"var {var_name} = dictPack{{", "\tAICliches: map[string]string{"]
    for k, v in sorted_items:
        k_esc = k.replace('"', '\\"')
        v_esc = v.replace('"', '\\"')
        lines.append(f'\t\t"{k_esc}": "{v_esc}",')
    lines.append("\t},")
    lines.append("\tFiller:   map[string]string{},")
    lines.append("\tUpgrades: map[string]string{},")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding='utf-8')


# =================================================================
# ENGLISH: Add thousands more entries
# =================================================================

EN_ULTIMATE = {
    # Idiomatic phrases and collocations
    "at all": "in any way",
    "at last": "ultimately",
    "at least": "minimally",
    "at most": "maximally",
    "at first": "initially",
    "at the moment": "presently",
    "at the same time": "concurrently",
    "by the way": "incidentally",
    "in fact": "actually",
    "in general": "overall",
    "in particular": "specifically",
    "in addition": "furthermore",
    "in spite of": "despite",
    "on the other hand": "conversely",
    "as a result": "consequently",
    "for example": "for instance",
    "in other words": "namely",
    "of course": "naturally",
    "as well": "additionally",
    "no doubt": "undoubtedly",

    # Phrasal verbs
    "give up": "relinquish",
    "give in": "capitulate",
    "give out": "distribute",
    "give back": "return",
    "take off": "depart",
    "take on": "assume",
    "take over": "appropriate",
    "take out": "extract",
    "take up": "embrace",
    "take down": "dismantle",
    "put on": "wear",
    "put off": "postpone",
    "put up": "erect",
    "put down": "deposit",
    "put away": "store",
    "put together": "assemble",
    "set up": "establish",
    "set off": "initiate",
    "set out": "embark",
    "set aside": "reserve",
    "set down": "record",
    "look up": "research",
    "look down": "disdain",
    "look after": "supervise",
    "look for": "seek",
    "look forward": "anticipate",
    "look over": "examine",
    "look into": "investigate",
    "look back": "reminisce",
    "look out": "beware",
    "look around": "survey",
    "come up": "emerge",
    "come down": "descend",
    "come back": "return",
    "come in": "enter",
    "come out": "emerge",
    "come along": "accompany",
    "come about": "transpire",
    "come across": "encounter",
    "come over": "approach",
    "come through": "succeed",
    "come together": "convene",
    "come apart": "disintegrate",
    "go on": "continue",
    "go off": "detonate",
    "go up": "ascend",
    "go down": "descend",
    "go through": "experience",
    "go back": "return",
    "go over": "review",
    "go away": "depart",
    "go ahead": "proceed",
    "go around": "circulate",
    "go beyond": "transcend",
    "go forward": "advance",
    "go forth": "proceed",
    "make up": "fabricate",
    "make out": "discern",
    "make over": "renovate",
    "make for": "head toward",
    "get up": "rise",
    "get down": "descend",
    "get out": "exit",
    "get in": "enter",
    "get on": "board",
    "get off": "disembark",
    "get back": "return",
    "get away": "escape",
    "get along": "harmonize",
    "get over": "recover",
    "get through": "survive",
    "get rid of": "discard",
    "turn on": "activate",
    "turn off": "deactivate",
    "turn up": "appear",
    "turn down": "decline",
    "turn over": "rotate",
    "turn around": "reverse",
    "turn back": "retreat",
    "turn into": "transform",
    "break down": "malfunction",
    "break up": "disintegrate",
    "break out": "erupt",
    "break in": "interrupt",
    "break off": "discontinue",
    "break through": "penetrate",
    "break away": "secede",
    "bring up": "introduce",
    "bring down": "topple",
    "bring out": "publish",
    "bring in": "introduce",
    "bring back": "restore",
    "bring about": "cause",
    "bring along": "accompany",
    "call off": "cancel",
    "call up": "summon",
    "call out": "denounce",
    "call back": "return call",
    "carry on": "continue",
    "carry out": "execute",
    "carry over": "transfer",
    "check in": "register",
    "check out": "depart",
    "check up": "examine",
    "fill in": "complete",
    "fill out": "complete",
    "fill up": "saturate",
    "hand in": "submit",
    "hand out": "distribute",
    "hand over": "surrender",
    "hold on": "endure",
    "hold up": "delay",
    "hold back": "restrain",
    "hold out": "persevere",
    "keep up": "maintain",
    "keep on": "persist",
    "keep out": "exclude",
    "keep away": "avoid",
    "let down": "disappoint",
    "let in": "admit",
    "let out": "release",
    "let off": "exempt",
    "pick up": "collect",
    "pick out": "select",
    "pick on": "harass",
    "point out": "indicate",
    "point at": "designate",
    "pull off": "accomplish",
    "pull out": "withdraw",
    "pull through": "survive",
    "pull up": "halt",
    "run away": "flee",
    "run into": "encounter",
    "run out": "deplete",
    "run over": "trample",
    "run through": "rehearse",
    "show off": "boast",
    "show up": "appear",
    "stand by": "support",
    "stand for": "represent",
    "stand out": "distinguish",
    "stand up": "rise",
    "wake up": "awaken",
    "wear out": "exhaust",
    "work out": "exercise",
    "work on": "develop",

    # More common nouns
    "advice": "counsel",
    "agreement": "consensus",
    "anger": "wrath",
    "approach": "methodology",
    "attempt": "endeavor",
    "attention": "scrutiny",
    "behavior": "demeanor",
    "belief": "conviction",
    "benefit": "advantage",
    "boss": "supervisor",
    "boundary": "demarcation",
    "branch": "subdivision",
    "career": "vocation",
    "chance": "opportunity",
    "circumstance": "situation",
    "claim": "assertion",
    "client": "patron",
    "comment": "observation",
    "competition": "rivalry",
    "concept": "notion",
    "concern": "apprehension",
    "conclusion": "deduction",
    "condition": "circumstance",
    "conference": "summit",
    "confidence": "assurance",
    "conflict": "discord",
    "connection": "linkage",
    "consequence": "ramification",
    "constitution": "charter",
    "context": "framework",
    "control": "dominion",
    "cooperation": "collaboration",
    "courage": "valor",
    "criticism": "censure",
    "current": "prevailing",
    "danger": "peril",
    "decision": "determination",
    "demand": "exigency",
    "depth": "profundity",
    "design": "schema",
    "destination": "terminus",
    "difference": "disparity",
    "difficulty": "predicament",
    "direction": "trajectory",
    "discount": "reduction",
    "discussion": "deliberation",
    "distance": "interval",
    "distinction": "differentiation",
    "diversity": "heterogeneity",
    "doubt": "uncertainty",
    "duty": "obligation",
    "edge": "perimeter",
    "education": "erudition",
    "effort": "exertion",
    "emotion": "sentiment",
    "energy": "vigor",
    "environment": "surroundings",
    "equality": "parity",
    "equipment": "apparatus",
    "error": "fallacy",
    "evidence": "corroboration",
    "exception": "anomaly",
    "experience": "expertise",
    "expert": "authority",
    "explanation": "elucidation",
    "extent": "magnitude",
    "failure": "downfall",
    "faith": "conviction",
    "feature": "characteristic",
    "feeling": "emotion",
    "freedom": "liberty",
    "function": "purpose",
    "future": "destiny",
    "gathering": "convocation",
    "growth": "augmentation",
    "habit": "custom",
    "happiness": "euphoria",
    "harm": "detriment",
    "health": "wellness",
    "height": "altitude",
    "history": "chronicle",
    "honor": "esteem",
    "hope": "aspiration",
    "humor": "wit",
    "idea": "notion",
    "image": "representation",
    "imagination": "creativity",
    "impact": "ramification",
    "importance": "significance",
    "impression": "perception",
    "improvement": "amelioration",
    "income": "earnings",
    "industry": "manufacturing",
    "influence": "sway",
    "information": "intelligence",
    "innovation": "novelty",
    "instance": "occurrence",
    "intention": "purpose",
    "interest": "fascination",
    "interview": "consultation",
    "introduction": "preamble",
    "investment": "endowment",
    "involvement": "participation",
    "judgment": "verdict",
    "justice": "equity",
    "knowledge": "erudition",
    "language": "vernacular",
    "leadership": "stewardship",
    "length": "duration",
    "lesson": "tutorial",
    "level": "echelon",
    "life": "existence",
    "limitation": "restriction",
    "loss": "deprivation",
    "loyalty": "fidelity",
    "majority": "preponderance",
    "manner": "comportment",
    "marriage": "matrimony",
    "matter": "substance",
    "meaning": "significance",
    "measure": "yardstick",
    "media": "communication",
    "meeting": "convention",
    "memory": "recollection",
    "method": "procedure",
    "minority": "fraction",
    "mistake": "blunder",
    "mood": "temperament",
    "motion": "movement",
    "motive": "rationale",
    "nature": "essence",
    "need": "necessity",
    "neighborhood": "vicinity",
    "object": "artifact",
    "objective": "aim",
    "obligation": "duty",
    "occasion": "event",
    "opinion": "viewpoint",
    "opportunity": "prospect",
    "opposition": "antagonism",
    "option": "alternative",
    "organization": "establishment",
    "outcome": "result",
    "ownership": "proprietorship",
    "passion": "ardor",
    "patience": "forbearance",
    "performance": "rendition",
    "permission": "authorization",
    "personality": "temperament",
    "perspective": "viewpoint",
    "place": "locale",
    "pleasure": "enjoyment",
    "policy": "stratagem",
    "popularity": "renown",
    "population": "demographic",
    "possibility": "feasibility",
    "potential": "capability",
    "poverty": "destitution",
    "practice": "rehearsal",
    "preference": "predilection",
    "presence": "attendance",
    "presentation": "exhibition",
    "pride": "vanity",
    "principle": "tenet",
    "priority": "precedence",
    "privilege": "prerogative",
    "process": "methodology",
    "professional": "expert",
    "profit": "yield",
    "progress": "advancement",
    "promise": "pledge",
    "promotion": "advancement",
    "proof": "verification",
    "property": "estate",
    "proposal": "submission",
    "protection": "preservation",
    "purpose": "intention",
    "quality": "caliber",
    "quantity": "amount",
    "rate": "tempo",
    "reaction": "response",
    "reality": "actuality",
    "reason": "rationale",
    "recognition": "acknowledgment",
    "reduction": "diminution",
    "reference": "citation",
    "reform": "rectification",
    "relationship": "association",
    "relief": "alleviation",
    "religion": "creed",
    "request": "petition",
    "research": "investigation",
    "resistance": "opposition",
    "responsibility": "accountability",
    "rest": "remainder",
    "result": "outcome",
    "return": "restoration",
    "revolution": "insurgence",
    "reward": "recompense",
    "right": "entitlement",
    "risk": "jeopardy",
    "role": "function",
    "rule": "regulation",
    "safety": "security",
    "satisfaction": "gratification",
    "scale": "magnitude",
    "scope": "ambit",
    "search": "quest",
    "security": "safeguard",
    "selection": "preference",
    "service": "amenity",
    "shape": "configuration",
    "share": "portion",
    "sign": "indication",
    "silence": "quiescence",
    "situation": "predicament",
    "skill": "aptitude",
    "society": "civilization",
    "solution": "remedy",
    "source": "origin",
    "space": "expanse",
    "speech": "oration",
    "spirit": "essence",
    "stability": "equilibrium",
    "stage": "platform",
    "standard": "criterion",
    "statement": "declaration",
    "status": "standing",
    "strategy": "stratagem",
    "strength": "vigor",
    "stress": "anxiety",
    "structure": "configuration",
    "study": "examination",
    "style": "aesthetic",
    "success": "triumph",
    "suggestion": "proposal",
    "support": "advocacy",
    "surface": "exterior",
    "surprise": "astonishment",
    "system": "methodology",
    "tactic": "stratagem",
    "task": "undertaking",
    "technique": "methodology",
    "technology": "innovation",
    "tendency": "inclination",
    "tension": "strain",
    "term": "interval",
    "territory": "domain",
    "test": "assessment",
    "theory": "hypothesis",
    "thought": "cogitation",
    "threat": "menace",
    "tip": "gratuity",
    "tool": "instrument",
    "tradition": "convention",
    "training": "instruction",
    "transformation": "metamorphosis",
    "treatment": "therapy",
    "trend": "vogue",
    "trial": "tribulation",
    "trouble": "predicament",
    "trust": "reliance",
    "truth": "veracity",
    "type": "genre",
    "uncertainty": "ambiguity",
    "understanding": "comprehension",
    "unity": "cohesion",
    "use": "utilization",
    "user": "operator",
    "validity": "legitimacy",
    "value": "worth",
    "variety": "diversity",
    "victory": "triumph",
    "view": "perspective",
    "violence": "brutality",
    "vision": "envisioning",
    "voice": "vocalization",
    "volume": "magnitude",
    "warning": "admonition",
    "wealth": "affluence",
    "welfare": "well-being",
    "wish": "aspiration",
    "wonder": "marvel",
    "worry": "consternation",
    "youth": "adolescence",

    # More adverbs
    "indeed": "veritably",
    "rather": "moderately",
    "somewhat": "moderately",
    "specifically": "particularly",
    "ultimately": "eventually",
    "unfortunately": "regrettably",
    "alternatively": "instead",
    "moreover": "furthermore",
    "nevertheless": "regardless",
    "nonetheless": "regardless",
    "consequently": "therefore",
    "accordingly": "appropriately",
    "subsequently": "thereafter",
    "previously": "antecedently",
    "presently": "currently",
    "currently": "presently",
    "recently": "latterly",
    "formerly": "previously",
    "lately": "of late",
    "previously": "beforehand",
    "thereafter": "subsequently",
    "henceforth": "from now on",

    # Time expressions
    "in the morning": "in the early hours",
    "in the afternoon": "in midday hours",
    "in the evening": "in late hours",
    "at night": "during nighttime",
    "all day": "throughout the day",
    "all night": "throughout the night",
    "every day": "daily",
    "every night": "nightly",
    "every week": "weekly",
    "every month": "monthly",
    "every year": "annually",
    "right now": "at this moment",
    "for now": "for the present",
    "for ever": "perpetually",
    "for a while": "for some time",
    "a long time ago": "in the distant past",

    # Question words
    "how come": "for what reason",
    "what for": "with what purpose",
    "what if": "supposing that",
    "where to": "to what destination",
    "where from": "from what origin",
    "how much": "what amount",
    "how many": "what quantity",
    "how long": "what duration",
    "how often": "with what frequency",
    "how far": "what distance",
}


# =================================================================
# RUSSIAN: Add thousands more entries
# =================================================================

RU_ULTIMATE = {
    # Common phrases
    "большое спасибо": "глубокая благодарность",
    "огромное спасибо": "величайшая признательность",
    "спасибо большое": "выражаю благодарность",
    "не за что": "пустяки",
    "пожалуйста": "будьте добры",
    "доброе утро": "превосходного утра",
    "добрый день": "превосходного дня",
    "добрый вечер": "превосходного вечера",
    "спокойной ночи": "безмятежной ночи",
    "до свидания": "прощайте",
    "до встречи": "до следующего раза",
    "всего хорошего": "наилучших пожеланий",
    "всего доброго": "благополучия вам",
    "удачи": "успехов",
    "счастливого пути": "благополучной дороги",
    "приятного аппетита": "приятной трапезы",
    "будьте здоровы": "сохраните здоровье",
    "извините": "приношу извинения",
    "простите": "прошу прощения",
    "как дела": "каково ваше самочувствие",
    "как поживаете": "как ваше благополучие",
    "что нового": "какие новости",
    "пока": "до скорого",
    "увидимся": "встретимся снова",

    # Common particles and modal words
    "конечно же": "разумеется",
    "разумеется": "несомненно",
    "безусловно": "категорически",
    "возможно": "предположительно",
    "наверное": "вероятно",
    "может быть": "потенциально",
    "вероятно": "возможно",
    "правда": "действительно",
    "действительно": "впрямь",
    "точно": "несомненно",
    "именно": "конкретно",
    "конкретно": "в частности",
    "в общем": "в целом",
    "в целом": "обобщённо",
    "в принципе": "теоретически",
    "по сути": "по существу",
    "по существу": "в основе своей",
    "на самом деле": "в действительности",
    "в действительности": "фактически",
    "фактически": "практически",
    "практически": "почти что",
    "по факту": "согласно фактам",
    "в любом случае": "при любых обстоятельствах",
    "так или иначе": "тем или иным образом",
    "тем не менее": "однако",
    "однако": "тем не менее",
    "впрочем": "хотя",
    "хотя": "несмотря на то что",
    "несмотря на": "невзирая на",
    "невзирая на": "вопреки",
    "вопреки": "наперекор",
    "благодаря": "вследствие",
    "вследствие": "из-за",
    "из-за": "по причине",
    "по причине": "ввиду",
    "ввиду": "по факту",
    "согласно": "в соответствии с",
    "в соответствии с": "сообразно",
    "наряду с": "наравне с",
    "помимо": "кроме",
    "кроме": "за исключением",
    "за исключением": "вне",

    # More common verb forms (compound forms)
    "буду делать": "стану осуществлять",
    "будет делать": "станет осуществлять",
    "будут делать": "станут осуществлять",
    "буду говорить": "стану сообщать",
    "будет говорить": "станет сообщать",
    "буду думать": "стану размышлять",
    "будет думать": "станет размышлять",
    "буду писать": "стану сочинять",
    "будет писать": "станет сочинять",
    "буду читать": "стану изучать",
    "будет читать": "станет изучать",
    "буду работать": "стану трудиться",
    "будет работать": "станет трудиться",

    # Past tense compound
    "сделал бы": "осуществил бы",
    "сделала бы": "осуществила бы",
    "сделали бы": "осуществили бы",
    "сказал бы": "произнёс бы",
    "сказала бы": "произнесла бы",
    "написал бы": "сочинил бы",
    "прочитал бы": "изучил бы",

    # More nouns
    "автомобиль": "транспортное средство",
    "автомобиля": "транспортного средства",
    "автомобилю": "транспортному средству",
    "автомобилем": "транспортным средством",
    "автомобили": "транспортные средства",
    "автомобилей": "транспортных средств",
    "автомобилям": "транспортным средствам",
    "автомобилями": "транспортными средствами",

    "холодильник": "охлаждающий аппарат",
    "телевизор": "телеприёмник",
    "компьютер": "вычислительная машина",
    "ноутбук": "переносной компьютер",
    "планшет": "сенсорное устройство",
    "клавиатура": "ввод-устройство",
    "мышь компьютерная": "указательное устройство",
    "монитор": "экран",
    "принтер": "печатное устройство",
    "сканер": "сканирующее устройство",
    "колонки": "акустическая система",
    "наушники": "ушные динамики",
    "микрофон": "звукозаписывающее устройство",

    # More body parts and health
    "температура": "термометрические показания",
    "давление": "артериальное давление",
    "пульс": "сердцебиение",
    "дыхание": "респирация",
    "сон": "состояние покоя",
    "питание": "рацион",
    "лечение": "терапия",
    "лекарство": "медикамент",
    "лекарства": "медикаменты",
    "таблетка": "пилюля",
    "таблетки": "пилюли",
    "укол": "инъекция",
    "уколы": "инъекции",
    "операция": "хирургическое вмешательство",
    "операции": "хирургические вмешательства",
    "процедура": "медицинское действие",
    "процедуры": "медицинские действия",
    "диагноз": "медицинское заключение",
    "диагнозы": "медицинские заключения",
    "анализ": "лабораторное исследование",
    "анализы": "лабораторные исследования",
    "рентген": "рентгеновский снимок",
    "узи": "ультразвуковое исследование",

    # Money and finance
    "рубль": "денежная единица",
    "рубли": "денежные единицы",
    "доллар": "американская валюта",
    "доллары": "американские валюты",
    "евро": "европейская валюта",
    "копейка": "мелкая монета",
    "копейки": "мелкие монеты",
    "цент": "стотая часть",
    "центы": "стотые части",
    "монета": "металлическая денежная единица",
    "монеты": "металлические денежные единицы",
    "купюра": "бумажная денежная единица",
    "купюры": "бумажные денежные единицы",
    "банкнота": "бумажная купюра",
    "банкноты": "бумажные купюры",
    "чек": "платёжный документ",
    "чеки": "платёжные документы",
    "счёт": "финансовый документ",
    "счета": "финансовые документы",
    "карта банковская": "платёжная карта",
    "кредит": "заём",
    "кредиты": "займы",
    "долг": "задолженность",
    "долги": "задолженности",
    "сбережения": "финансовые накопления",
    "вклад": "депозит",
    "вклады": "депозиты",
    "процент": "доля",
    "проценты": "доли",
    "налог": "обязательный платёж",
    "налоги": "обязательные платежи",
    "зарплата": "оклад",
    "зарплаты": "оклады",
    "премия": "бонус",
    "премии": "бонусы",
    "пенсия": "социальное обеспечение",
    "пенсии": "социальные обеспечения",
    "доход": "прибыль",
    "доходы": "прибыли",
    "расход": "издержка",
    "расходы": "издержки",
    "бюджет": "финансовый план",
    "бюджеты": "финансовые планы",

    # Education detailed
    "детский сад": "дошкольное учреждение",
    "детские сады": "дошкольные учреждения",
    "школа начальная": "начальное учебное заведение",
    "школа средняя": "среднее учебное заведение",
    "колледж": "среднее специальное учебное заведение",
    "колледжи": "средние специальные учебные заведения",
    "университет": "высшее учебное заведение",
    "университеты": "высшие учебные заведения",
    "институт": "научно-исследовательское учреждение",
    "институты": "научно-исследовательские учреждения",
    "академия": "высшая академическая школа",
    "академии": "высшие академические школы",
    "факультет": "подразделение",
    "факультеты": "подразделения",
    "кафедра": "учебная единица",
    "кафедры": "учебные единицы",
    "лекция": "учебное выступление",
    "лекции": "учебные выступления",
    "семинар": "практическое занятие",
    "семинары": "практические занятия",
    "лабораторная": "лабораторное занятие",
    "лабораторные": "лабораторные занятия",
    "практика": "профессиональная стажировка",
    "практики": "профессиональные стажировки",
    "курсовая": "курсовая работа",
    "курсовые": "курсовые работы",
    "дипломная": "дипломная работа",
    "дипломные": "дипломные работы",
    "диссертация": "научная работа",
    "диссертации": "научные работы",
    "степень": "учёная степень",
    "степени": "учёные степени",
    "диплом": "документ об образовании",
    "дипломы": "документы об образовании",
    "сертификат": "удостоверение",
    "сертификаты": "удостоверения",

    # Sports and games
    "футбол": "командная игра с мячом",
    "хоккей": "игра на льду",
    "баскетбол": "игра с корзиной",
    "волейбол": "игра с сеткой",
    "теннис": "игра ракеткой",
    "плавание": "водное состязание",
    "бег": "лёгкая атлетика",
    "ходьба": "перемещение пешком",
    "велоспорт": "велогонки",
    "лыжи": "зимний спорт",
    "коньки": "ледовые конки",
    "шахматы": "интеллектуальная игра",
    "карты": "карточные игры",
    "бильярд": "игра кием",
    "боулинг": "игра с шарами",
    "гольф": "клюшечная игра",

    # Weather
    "солнечно": "ясная погода",
    "пасмурно": "облачно",
    "дождливо": "осадки",
    "снежно": "снегопад",
    "ветрено": "сильный ветер",
    "морозно": "ниже нуля",
    "жарко": "высокая температура",
    "тепло": "комфортная температура",
    "прохладно": "пониженная температура",
    "холодно": "низкая температура",
    "сыро": "повышенная влажность",
    "сухо": "пониженная влажность",
    "облако": "облачное скопление",
    "облака": "облачные скопления",
    "туча": "тёмное облако",
    "тучи": "тёмные облака",
    "радуга": "оптический феномен",
    "радуги": "оптические феномены",
    "иней": "ледяной налёт",
    "роса": "утренняя влага",
    "ливень": "сильный дождь",
    "ливни": "сильные дожди",

    # Emotions and states
    "восторг": "восхищение",
    "восторга": "восхищения",
    "восхищение": "благоговение",
    "удивление": "изумление",
    "удивления": "изумления",
    "изумление": "потрясение",
    "потрясение": "шок",
    "шок": "сильное потрясение",
    "ужас": "крайний страх",
    "ужаса": "крайнего страха",
    "паника": "массовый страх",
    "паники": "массового страха",
    "тревога": "беспокойство",
    "тревоги": "беспокойства",
    "беспокойство": "волнение",
    "беспокойства": "волнения",
    "волнение": "трепет",
    "волнения": "трепеты",
    "разочарование": "огорчение",
    "разочарования": "огорчения",
    "огорчение": "печаль",
    "обида": "оскорбление",
    "обиды": "оскорбления",
    "негодование": "возмущение",
    "негодования": "возмущения",
    "возмущение": "гнев",
    "возмущения": "гневы",
    "ярость": "ярость гневная",
    "ярости": "ярости гневные",
    "бешенство": "ярость безудержная",
    "благодарность": "признательность",
    "благодарности": "признательности",
    "признательность": "благодарение",
    "уважение": "почтение",
    "уважения": "почтения",
    "почтение": "благоговение",
    "восхищение": "благоговение",
    "удовольствие": "наслаждение",
    "удовольствия": "наслаждения",
    "наслаждение": "услада",
    "наслаждения": "услады",
    "удовлетворение": "удовлетворённость",
    "удовлетворения": "удовлетворённости",

    # Common Russian adjectives - full forms
    "сложного": "запутанного",
    "сложному": "запутанному",
    "сложным": "запутанным",
    "сложной": "запутанной",
    "сложных": "запутанных",
    "сложными": "запутанными",
    "простого": "элементарного",
    "простому": "элементарному",
    "простым": "элементарным",
    "простой": "элементарной",
    "простых": "элементарных",
    "простыми": "элементарными",
    "тяжёлого": "тяжеловесного",
    "тяжёлому": "тяжеловесному",
    "тяжёлым": "тяжеловесным",
    "тяжёлой": "тяжеловесной",
    "тяжёлых": "тяжеловесных",
    "тяжёлыми": "тяжеловесными",
    "лёгкого": "необременительного",
    "лёгкому": "необременительному",
    "лёгким": "необременительным",
    "лёгкой": "необременительной",
    "лёгких": "необременительных",
    "лёгкими": "необременительными",
}


# =================================================================
# MOLDOVAN: Add thousands more entries
# =================================================================

MO_ULTIMATE = {
    # Common phrases
    "bună dimineața": "salutări matinale",
    "bună ziua": "salutări diurne",
    "bună seara": "salutări vesperale",
    "noapte bună": "noapte senină",
    "la revedere": "rămas bun",
    "pe curând": "pe curând să ne revedem",
    "ne vedem": "ne vom revedea",
    "mulțumesc mult": "îmi exprim profunda recunoștință",
    "mulțumesc frumos": "îți mulțumesc cordial",
    "vă rog frumos": "vă solicit cu respect",
    "te rog frumos": "îți solicit cu respect",
    "îmi pare rău": "îmi exprim regretul",
    "îmi cer scuze": "îmi exprim căința",
    "nu știu": "nu sunt informat",
    "nu înțeleg": "nu sesizez",
    "așa este": "este corect",
    "nu este așa": "nu este corect",
    "ce mai faci": "cum te simți",
    "cum te simți": "care e starea ta",
    "totul bine": "totul în ordine",

    # More verbs with all forms
    "salut": "îmi exprim salutul", "saluți": "îți exprimi salutul",
    "felicitez": "complimentez", "felicităm": "complimentăm",
    "iert": "absolv", "ierți": "absolvi", "iertăm": "absolvim",
    "promit": "făgăduiesc", "promiți": "făgăduiești",
    "jur": "atest solemn", "juri": "atestă solemn",
    "rog": "implor", "rogi": "implori", "rugăm": "implorăm",
    "ascult": "aud cu atenție", "asculți": "auzi cu atenție",
    "spun": "comunic", "spui": "comunici", "spunem": "comunicăm",
    "vorbesc": "comunic verbal", "vorbești": "comunici verbal",
    "tac": "păstrez tăcerea", "taci": "păstrezi tăcerea",
    "strig": "vociferez", "strigi": "vociferezi", "strigăm": "vociferăm",
    "șoptesc": "murmur", "șoptești": "murmuri", "șoptim": "murmurăm",
    "râd": "hohotesc", "râzi": "hohotești", "râdem": "hohotim",
    "plâng": "lăcrimez", "plângi": "lăcrimezi", "plângem": "lăcrimăm",
    "zâmbesc": "schițez un surâs", "zâmbești": "schițezi un surâs",
    "iubesc": "ador", "iubești": "adori", "iubim": "adorăm",
    "urăsc": "detest", "urăști": "detești", "urâm": "detestăm",
    "respect": "venerez", "respecți": "venerezi", "respectăm": "venerăm",
    "admir": "stimez", "admiri": "stimezi", "admirăm": "stimăm",
    "disprețuiesc": "desconsider", "disprețuiești": "desconsideri",
    "îndoiesc": "ezit", "îndoiești": "eziți", "îndoim": "ezităm",
    "cred": "consider", "crezi": "consideri", "credem": "considerăm",
    "doresc": "tânjesc", "dorești": "tânjești", "dorim": "tânjim",
    "vreau": "aspir", "vrei": "aspiri", "vrem": "aspirăm",
    "pot": "sunt capabil", "poți": "ești capabil", "putem": "suntem capabili",
    "trebuie": "este necesar", "trebuiau": "erau necesare",
    "îmi place": "îmi este pe plac", "îi place": "îi este pe plac",
    "îmi pare": "îmi se pare", "îți pare": "îți se pare",

    # Months
    "ianuarie": "prima lună a anului",
    "februarie": "a doua lună a anului",
    "martie": "a treia lună a anului",
    "aprilie": "a patra lună a anului",
    "mai": "a cincea lună a anului",
    "iunie": "a șasea lună a anului",
    "iulie": "a șaptea lună a anului",
    "august": "a opta lună a anului",
    "septembrie": "a noua lună a anului",
    "octombrie": "a zecea lună a anului",
    "noiembrie": "a unsprezecea lună a anului",
    "decembrie": "a douăsprezecea lună a anului",

    # Days of week
    "luni": "ziua întâi a săptămânii",
    "marți": "ziua a doua a săptămânii",
    "miercuri": "ziua a treia a săptămânii",
    "joi": "ziua a patra a săptămânii",
    "vineri": "ziua a cincea a săptămânii",
    "sâmbătă": "ziua a șasea a săptămânii",
    "duminică": "ziua a șaptea a săptămânii",

    # Seasons
    "primăvară": "anotimp de revigorare",
    "primăvara": "anotimpul de revigorare",
    "vară": "anotimp călduros",
    "vara": "anotimpul călduros",
    "toamnă": "anotimp de tranziție",
    "toamna": "anotimpul de tranziție",
    "iarnă": "anotimp rece",
    "iarna": "anotimpul rece",

    # Numbers
    "zero": "nimic", "unu": "singular",
    "doi": "pereche", "doua": "pereche",
    "trei": "trio", "patru": "cvartet",
    "cinci": "cvintet", "șase": "sextet",
    "șapte": "septet", "opt": "octet",
    "nouă": "nonet", "zece": "decadă",
    "unsprezece": "11 unități", "doisprezece": "duzină",
    "treisprezece": "13 unități", "paisprezece": "14 unități",
    "cincisprezece": "15 unități", "șaisprezece": "16 unități",
    "șaptesprezece": "17 unități", "optsprezece": "18 unități",
    "nouăsprezece": "19 unități", "douăzeci": "20 unități",
    "treizeci": "30 unități", "patruzeci": "40 unități",
    "cincizeci": "50 unități", "șaizeci": "60 unități",
    "șaptezeci": "70 unități", "optzeci": "80 unități",
    "nouăzeci": "90 unități", "sută": "centenar",
    "o sută": "centenar", "mie": "miliar",
    "o mie": "miliar", "milion": "un milion",

    # Family
    "tată": "părinte patern", "tatăl": "părintele patern",
    "mamă": "părinte matern", "mama": "părintele matern",
    "fiu": "moștenitor masculin", "fiul": "moștenitorul masculin",
    "fiică": "moștenitor feminin", "fiica": "moștenitorul feminin",
    "frate": "consanguin masculin", "fratele": "consanguinul masculin",
    "soră": "consanguin feminin", "sora": "consanguinul feminin",
    "bunic": "ascendent matur", "bunicul": "ascendentul matur",
    "bunică": "ascendentă matură", "bunica": "ascendenta matură",
    "nepot": "descendent direct", "nepotul": "descendentul direct",
    "nepoată": "descendentă directă", "nepoata": "descendenta directă",
    "unchi": "rudă paternă", "unchiul": "ruda paternă",
    "mătușă": "rudă maternă", "mătușa": "ruda maternă",
    "verișor": "rudă colaterală", "verișorul": "ruda colaterală",
    "soț": "partener marital", "soțul": "partenerul marital",
    "soție": "parteneră maritală", "soția": "partenera maritală",

    # Common state words
    "obosit": "epuizat", "obosită": "epuizată",
    "odihnit": "refăcut", "odihnită": "refăcută",
    "flămând": "famelic", "flămândă": "famelică",
    "sătul": "saturat", "sătulă": "saturată",
    "însetat": "deshidratat", "însetată": "deshidratată",
    "trezit": "deșteptat", "trezită": "deșteptată",
    "adormit": "în somn", "adormită": "în somn",
    "vesel": "jovial", "veselă": "jovială",
    "trist": "melancolic", "tristă": "melancolică",
    "supărat": "iritat", "supărată": "iritată",
    "calm": "imperturbabil", "calmă": "imperturbabilă",
    "agitat": "neliniștit", "agitată": "neliniștită",
    "speriat": "înfricoșat", "speriată": "înfricoșată",
    "curios": "iscoditor", "curioasă": "iscoditoare",
    "uimit": "stupefiat", "uimită": "stupefiată",
    "mirat": "uimit", "mirată": "uimită",
    "îngrijorat": "preocupat", "îngrijorată": "preocupată",
    "mulțumit": "satisfăcut", "mulțumită": "satisfăcută",
    "nemulțumit": "nesatisfăcut", "nemulțumită": "nesatisfăcută",
    "îndrăgostit": "atras erotic", "îndrăgostită": "atrasă erotic",
    "gelos": "invidios", "geloasă": "invidioasă",
    "mândru": "demn", "mândră": "demnă",
    "rușinat": "stânjenit", "rușinată": "stânjenită",
    "vinovat": "culpabil", "vinovată": "culpabilă",
    "nevinovat": "fără culpă", "nevinovată": "fără culpă",

    # Education
    "școală": "instituție de învățământ",
    "școala": "instituția de învățământ",
    "grădiniță": "instituție preșcolară",
    "grădinița": "instituția preșcolară",
    "liceu": "instituție de învățământ secundar",
    "liceul": "instituția de învățământ secundar",
    "universitate": "instituție de învățământ superior",
    "universitatea": "instituția de învățământ superior",
    "facultate": "subdiviziune universitară",
    "facultatea": "subdiviziunea universitară",
    "lecție": "instruire",
    "lecția": "instruirea",
    "lecții": "instruiri",
    "lecțiile": "instruirile",
    "curs": "ciclu de instruire",
    "cursul": "ciclul de instruire",
    "cursuri": "cicluri de instruire",
    "cursurile": "ciclurile de instruire",
    "examen": "verificare",
    "examenul": "verificarea",
    "examene": "verificări",
    "examenele": "verificările",
    "test": "evaluare",
    "testul": "evaluarea",
    "teste": "evaluări",
    "testele": "evaluările",
    "notă": "calificativ",
    "nota": "calificativul",
    "note": "calificative",
    "notele": "calificativele",
    "diplomă": "act de absolvire",
    "diploma": "actul de absolvire",
    "certificat": "atestat",
    "certificatul": "atestatul",
    "manual": "instrument didactic",
    "manualul": "instrumentul didactic",
    "manuale": "instrumente didactice",
    "manualele": "instrumentele didactice",
    "dicționar": "lexicon",
    "dicționarul": "lexiconul",
    "enciclopedie": "compendium",
    "enciclopedia": "compendiul",

    # Health
    "sănătate": "stare de bine fizic",
    "sănătatea": "starea de bine fizic",
    "boală": "afecțiune medicală",
    "boala": "afecțiunea medicală",
    "boli": "afecțiuni medicale",
    "bolile": "afecțiunile medicale",
    "durere": "suferință corporală",
    "durerea": "suferința corporală",
    "dureri": "suferințe corporale",
    "durerile": "suferințele corporale",
    "febră": "stare febrilă",
    "febra": "starea febrilă",
    "temperatură": "indicator termometric",
    "temperatura": "indicatorul termometric",
    "tuse": "simptom respirator",
    "tusea": "simptomul respirator",
    "alergie": "hipersensibilitate",
    "alergia": "hipersensibilitatea",
    "alergii": "hipersensibilități",
    "alergiile": "hipersensibilitățile",
    "rană": "vătămare corporală",
    "rana": "vătămarea corporală",
    "răni": "vătămări corporale",
    "rănile": "vătămările corporale",
    "tratament": "terapie medicală",
    "tratamentul": "terapia medicală",
    "tratamente": "terapii medicale",
    "tratamentele": "terapiile medicale",
    "operație": "intervenție chirurgicală",
    "operația": "intervenția chirurgicală",
    "operații": "intervenții chirurgicale",
    "operațiile": "intervențiile chirurgicale",
    "medicament": "preparat farmaceutic",
    "medicamentul": "preparatul farmaceutic",
    "medicamente": "preparate farmaceutice",
    "medicamentele": "preparatele farmaceutice",
    "pastilă": "preparat solid",
    "pastila": "preparatul solid",
    "pastile": "preparate solide",
    "pastilele": "preparatele solide",
    "vaccin": "imunizare",
    "vaccinul": "imunizarea",

    # Money
    "leu": "moneda națională",
    "leul": "moneda națională",
    "lei": "monede naționale",
    "ban": "monedă mică",
    "banul": "moneda mică",
    "bani": "mijloace de plată",
    "monedă": "piesă de schimb",
    "moneda": "piesa de schimb",
    "bancnotă": "hârtie monetară",
    "bancnota": "hârtia monetară",
    "card bancar": "instrument de plată",
    "credit": "împrumut",
    "creditul": "împrumutul",
    "credite": "împrumuturi",
    "creditele": "împrumuturile",
    "datorie": "obligație financiară",
    "datoria": "obligația financiară",
    "datorii": "obligații financiare",
    "datoriile": "obligațiile financiare",
    "salariu": "remunerație",
    "salariul": "remunerația",
    "salarii": "remunerații",
    "salariile": "remunerațiile",
    "preț": "valoare monetară",
    "prețul": "valoarea monetară",
    "prețuri": "valori monetare",
    "prețurile": "valorile monetare",
    "factură": "document de plată",
    "factura": "documentul de plată",
    "facturi": "documente de plată",
    "facturile": "documentele de plată",
    "impozit": "obligație fiscală",
    "impozitul": "obligația fiscală",
    "impozite": "obligații fiscale",
    "impozitele": "obligațiile fiscale",

    # Technology
    "telefon": "dispozitiv de comunicare",
    "telefonul": "dispozitivul de comunicare",
    "telefoane": "dispozitive de comunicare",
    "telefoanele": "dispozitivele de comunicare",
    "calculator": "dispozitiv electronic",
    "calculatorul": "dispozitivul electronic",
    "laptop": "computer portabil",
    "laptopul": "computerul portabil",
    "tabletă": "computer cu ecran tactil",
    "tableta": "computerul cu ecran tactil",
    "ecran": "afișaj",
    "ecranul": "afișajul",
    "tastatură": "dispozitiv de intrare",
    "tastatura": "dispozitivul de intrare",
    "mouse": "dispozitiv indicator",
    "imprimantă": "dispozitiv de tipărire",
    "imprimanta": "dispozitivul de tipărire",
    "scaner": "dispozitiv de scanare",
    "scanerul": "dispozitivul de scanare",
    "internet": "rețea globală",
    "internetul": "rețeaua globală",
    "site": "portal web",
    "siteul": "portalul web",
    "email": "poștă electronică",
    "emailul": "poșta electronică",
    "mesaj": "comunicare scrisă",
    "mesajul": "comunicarea scrisă",
    "mesaje": "comunicări scrise",
    "mesajele": "comunicările scrise",

    # Common adverbs more
    "exact": "precis",
    "aproape": "în proximitate",
    "departe": "la distanță mare",
    "sus": "în zona superioară",
    "jos": "în zona inferioară",
    "afară": "în exterior",
    "înăuntru": "în interior",
    "deasupra": "în partea superioară",
    "dedesubt": "în partea inferioară",
    "împreună": "în comun",
    "separat": "în mod individual",
    "mereu": "în continuu",
    "uneori": "în mod ocazional",
    "deseori": "cu frecvență mare",
    "rareori": "cu frecvență mică",
    "niciodată": "în niciun moment",
}


def expand_english():
    print("Expanding English...")
    existing = extract_existing(DICT_DIR / "dict_en.go")
    print(f"  Before: {len(existing)}")
    existing.update(EN_ULTIMATE)
    print(f"  After: {len(existing)}")
    write_dict(
        DICT_DIR / "dict_en.go",
        "synPack",
        "// synPack is the English synonym dictionary.\n// Comprehensive coverage: verbs, phrasal verbs, idioms, adjectives, adverbs,\n// nouns, time expressions, question words, and common phrases.",
        existing
    )
    return len(existing)


def expand_russian():
    print("Expanding Russian...")
    existing = extract_existing(DICT_DIR / "dict_ru.go")
    print(f"  Before: {len(existing)}")
    existing.update(RU_ULTIMATE)
    print(f"  After: {len(existing)}")
    write_dict(
        DICT_DIR / "dict_ru.go",
        "synPackRu",
        "// synPackRu is the Russian synonym dictionary.\n// Comprehensive coverage: greetings, particles, verbs (all forms),\n// nouns (all cases), adjectives, finance, education, health, emotions.",
        existing
    )
    return len(existing)


def expand_moldovan():
    print("Expanding Moldovan...")
    existing = extract_existing(DICT_DIR / "dict_mo.go")
    print(f"  Before: {len(existing)}")
    existing.update(MO_ULTIMATE)
    print(f"  After: {len(existing)}")
    write_dict(
        DICT_DIR / "dict_mo.go",
        "synPackMo",
        "// synPackMo is the Moldovan/Romanian synonym dictionary.\n// Comprehensive coverage: verbs (all forms), articulated/indefinite nouns,\n// adjectives, months, days, seasons, family, health, technology, money.",
        existing
    )
    return len(existing)


if __name__ == "__main__":
    en = expand_english()
    ru = expand_russian()
    mo = expand_moldovan()
    print(f"\n{'='*50}")
    print(f"EN: {en}")
    print(f"RU: {ru}")
    print(f"MO: {mo}")
    print(f"TOTAL: {en + ru + mo}")
